### ISSUE TITLE
Uncaught TypeError: Illegal invocation in jsdom

### ISSUE THREAD

**Issue by mangecoeur** [mathjax/MathJax-node#101]
I've been trying to use MathJax-node from within an Atom.io package (https://atom.io/packages/preview-inline) however even the basic example gives me `Uncaught TypeError: Illegal invocation` in `stopTimer` in jsdom:34 . 

Running the scripts in the bin/ folder gives

```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
```

Not sure what that refers to. Perhaps related to atom.io using io.js internally rather than node.js?

**Comment by mangecoeur** [comment]
Update: seems to be related to use of Jsdom 3.x , which is incompatible with io.js used in Atom.io . Made a fork to try with Jsdom 5.5, seems to get further although now i get `Refused to evaluate a string as JavaScript`

**Comment by pkra** [comment]
Thanks for the feedback. 

> Made a fork to try with Jsdom 5.5, 

Here, "a fork" refers to a fork of MathJax-node where you've upgraded to jsdom 5.5, correct?

**Comment by mangecoeur** [comment]
Yes I made a github fork and bumped the version. Though I ran into new problems related to atoms content security policy and jsdom... Still looking into that...

-----Original Message-----

**Comment by pkra** [comment]
> Yes I made a github fork and bumped the version.

Thanks for confirming.

> Though I ran into new problems related to atoms content security policy and jsdom.

Right. IIRC there are still some `eval` calls around for legacy browser support. If this is the problem, maybe we can tweak the MathJax branch used in MathJax-node to work around that.

**Comment by mangecoeur** [comment]
If that's possible it would be great. I've been really struggling with this much more than I expected - just trying to get `mjAPI.typeset()` to work in atom has been a bit of a rabbit hole of incompatible node/jsdom versions, CSP issues, and more... although we're having a heatwave so my it might just be my brain malfunctioning :P

**Comment by pkra** [comment]
> although we're having a heatwave so my it might just be my brain malfunctioning :P 

hehe. I can relate.

>  just trying to get mjAPI.typeset() to work in atom has been a bit of a rabbit hole of incompatible node/jsdom versions, CSP issues, and more...

@mangecoeur not sure if that might help but https://github.com/Galadirith/markdown-preview-plus integrates MathJax; maybe that's something to look at?

(@dpvc any immediate ideas how to avoid the `eval`/CSP issues?)

**Comment by dpvc** [comment]
> any immediate ideas how to avoid the eval/CSP issues?

The MathJax-node configuration does not use `eval` (unless the author includes a callback with a string rather than a function), so I'm wondering if this is coming from somewhere else.

Perhaps @mangecoeur can provide a little more detail about how he has integrated the two projects?  it is hard to give any meaningful advice in the absence of that.

**Comment by pkra** [comment]
Closing this as abandoned. We're still interested in hearing if our improvements have helped.

**Comment by xuyumeng** [comment]
A workaround is proposed by jdthorpe in [Illegal Invocation error when used in a web-worker](https://www.bountysource.com/issues/41781187-illegal-invocation-error-when-used-in-a-web-worker), but this line number is changed. So if you want to correct it. you need to change 

```JS
timer[1].call(window, timer[0]);
```
  
  in line 491 of `node_modules/jsdom/lib/jsdom/browser/Window.js` to
  ```JS
  var stopfn = timer[1];
  stopfn(timer[0]);
  ```
