### ISSUE TITLE
SVG width incorrect for equations with newline outside environment

### ISSUE THREAD

**Issue by sammarshallou** [mathjax/MathJax-node#104]
When you use the TeX newline symbol `\\` without a suitable environment such as `\begin{array}`, this results in SVG equations that are infeasibly wide.

Arguably it might be considered incorrect TeX to do `\\` without being in an environment, but our authors are in the habit of it.

The same problem does not appear to apply to client-side MathJax as tested on http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic.html

Example equation:

    a \\ b

On the above URL this works fine but if you run `./tex2svg 'a\\b'` (tested on Unix command line using current release version of MathJax.node 0.3.0) then the result begins:

    <svg xmlns:xlink="http://www.w3.org/1999/xlink" style="vertical-align: -2.833ex;
        margin-left: 0ex; margin-right: 0ex; margin-bottom: 1px; margin-top: 1px;"
        width="2322.667ex" height="4ex"
        viewBox="0 -464.9 1000000 1699.9" xmlns="http://www.w3.org/2000/svg">

Aside from being (I guess) 10,000 pixels wide, the output appears to be correct, with 'a' above 'b', but they're shown in the centre of this large equation space.

**Comment by pkra** [comment]
Thanks for reporting this. Looks like a mathjax-node specific bug.

**Comment by dpvc** [comment]
For now, you can do either

    ./tex2svg --linbreaks 'a\\b'

if you want to consider this a displayed equation (100ex wide), or 

    ./tex2svg --inline 'a\\b'

to get the in-line version (trimmed to the size of the two lines).

The issue turns out to be that the line breaking code uses a large number (10000000) as the width of the line when no line breaking is desired, and the line-breaking code looks for that value as a special case.  Unfortunately, the mj-single.js file was setting the value 1000000, one zero too few, so ironically, the width was too *small* to be picked up as meaning no automatic line breaks, and it was used as the actual width instead.

The commit listed above fixes the problem.  But you can also use the two commands above if you prefer.

**Comment by sammarshallou** [comment]
Thanks very much for fixing this so quickly! I tested the patch and it seems to work, specifically:

1 For equations without a newline, they get a width matching the equation (existing behaviour)
2 For equations with a newline, they get a width set to default 100ex, or the --width value if specified

Also thanks for the hint about `--inline`. As you probably guessed, the effect we really want is that equations with a newline behave the same as equations without a newline, i.e. the width matches the equation and not a fixed value. I think in order to achieve that without changing the styling, I basically need to use `--inline`, and insert `\displaystyle` at the start of the TeX. As a bonus it seems like that will work in the current code.

**Comment by dpvc** [comment]
> I basically need to use `--inline`, and insert `\displaystyle` at the start of the TeX.

In addition, I would recommend putting the math in braces following the `\displaystyle`.  That will prevent the `\displaystyle` from being localized to the beginning of the equation and not the end.  For example

    \displaystyle \sum_n \over \sum_m

will only have the first `\sum` in display mode.  Similarly,

    \displaystyle \sum_n \\ \sum_m

will end `\displaystyle` at the `\\`, while

    \displaystyle {\sum_n \\ \sum_m}

will put both sums in display style.

> As a bonus it seems like that will work in the current code.

Correct.

**Comment by sammarshallou** [comment]
Oops! Thanks again, will do.

**Comment by pkra** [comment]
This has been fixed in v0.4.0
