### ISSUE TITLE
does mathjax node server support high concurrency?

### ISSUE THREAD

**Issue by macarthor** [mathjax/MathJax-node#107]
hi all,

i've setup a mathjax nodejs server with the following sample server.js:

```
var childprocess = require("child_process"),
        express = require("express"),
        mathjax = require("../lib/mj-single.js");;
var port = 18686;
var _res;
var _mathml;
var _latex;

try {
        var app = express();
        app.listen(port);
        console.log("nodejs listening on port: " + port);
        app.get("/mathjax", callbackget);
} catch (err) {
        console.log(err);
}

function callbackget(req, res) {
        printLocalTime("get a mathml request");
        var mathml = req.query.mathml;
        var latex = req.query.latex;
        if (undefined != mathml) {
                callbackmathml(req, res, mathml);
                return;
        } else if (undefined != latex) {
                callbacklatex(req, res, latex);
        } else {
                res.send("calling mathjax with http get: no \"mathml\" nor \"latex\" argument");
        }
}

function callbackmathml(req, res, mathml) {
        //console.log("get a mathml = " + mathml);
        _res = res;
        _mathml = mathml;
        callcommand(mathml, null);
}

function callcommand(mathml, latex) {
        var command;
        var args;
        if (null == latex) {
                command = "../bin/mml2svg";
                args = [mathml];
        } else if (null == mathml) {
                command = "../bin/tex2svg";
                args = [latex];
        }
        var options = { maxBuffer : 1024 * 1024 };
        printLocalTime("going to call mml2svg");
        childprocess.execFile(command, args, options, function(error, stdout, stderr) {
                if (undefined != error || null != error) {
                        printLocalTime("mml2svg error");
                        console.log("error.code = " + error.code);
                        console.log("stderr = " + stderr);
                        //console.log("bad http-get argument?");
                        _res.send("bad http-get argument? ");
                } else {
                        printLocalTime("mml2svg ok");
                        //console.log("seding response = " + stdout);
                        _res.send(stdout);
                }
        });
}
```

when i use `ab -r -c 10 -n 10 "http://127.0.0.1:18686/mathjax?mathml=<some mathml>"` to benchmark the nodejs server, the `htop` command shows very high disk I/O, and the benchmark fails due to the I/O. when i use `ab -r -c 1` or `ab -r -c 3 -n 3`, the benchmark runs ok without seeing too much disk I/O.

any ideas to have mathjax nodejs server support high concurrency? say, 1K or 10K per second.

many thx!

**Comment by macarthor** [comment]
if i use mathjax-server (https://github.com/tiarno/mathjax-server), the benchmark gives the same result as above.

**Comment by macarthor** [comment]
it seems nodejs occupies too much RAM and begins to write to swap.

but another problem is that mathjax seems to take too much memory? i use `ab -r -c 10 -n 100` and nodejs takes about 2GB RAM, and `ab -r -c 30 -n 100` for more than 4GB.

any hints?

**Comment by pkra** [comment]
I'm not sure what you're after. Questions around concurrency with Nodejs probably fit better on StackOverflow. If you're simply asking about MathJax-node speed then that's a different question. It's difficult to answer as it depends largely on the complexity of the equations; http://arxiv.org/abs/1404.6179 has some data.

**Comment by dpvc** [comment]
Your server is calling the MathJax command-line tools `tex2svg` and `mml2svg`, which means that each request has to start up a separate process that loads all of MathJax to handle the one equation.  That is not very efficient, and will certainly take up a lot of memory.

You may get a better result if you set up and call the MathJax API directly (the command line tools are just examples of how that is done).  The server you mention in your second message does that, if I recall correctly, so the results there should be better.

Note, however, that MathJax takes time to process the equations, and (depending on the complexity) probably won't handle more than a couple of hundred equations per second.  You certainly will not be able to process 10K per second.  The MathJax API does queue the requests as they come in, so if you try to do 10K at a time, it will need to store those requests, and that will increase its memory usage.

It is also quite possible that there are memory leaks in jsdom or MathJax itself that will cause memory usage to grow over time.

Finally, be sure to use the develop branch if you are interested in highest speed, as there was a timing issue that caused unwanted delays that has been resolved there but not yet in master.

**Comment by macarthor** [comment]
@dpvc hi you are right, i was calling mml2svg before. when i use mathjax-node API js, it's much more better, the RAM consumption is about 1.2GB stably.

another question is that the concurrency of processing MathML equations is low: i ran on a i5-4450 quad core CPU + 4GB RAM hyper-v VM, 50 requests per seconds gives the best failure rate of 0% failure, but the concurrency is 4.03 request processed per second. i cannot imagine the case of 10K requests per second...

AFAIK, MathML to SVG is a CPU intensive job, so the concurrency of Mathjax-node is limited by CPU but not by RAM, etc. So the concurrency may not be very high.

**Comment by pkra** [comment]
I don't see anything actionable from this discussion (i.e., no bug or feature request) so closing this (but happy to continue the discussion here or elsewhere).
