### ISSUE TITLE
Guidance on using jsdom with Mathjax-node

### ISSUE THREAD

**Issue by colbygk** [mathjax/MathJax-node#109]
Do you have guidance on using jsdom with mathjax-node? Currently, when trying to use jsdom ~ 3.x, I see errors just trying to get jsdom to install on ubuntu 14.04 LTS using npm, erroring out in node-gyp. I've been going in circles this afternoon trying to get jsdom to install/be usable, including attempting to use iojs without much success.

**Comment by pkra** [comment]
Sorry to hear you've run into problems. Can you share those error messages? How did you install node and node-gyp? node-gyp needs several ubuntu packages installed, e.g., `build-essential` so you might want to search around which ones exactly.

**Comment by colbygk** [comment]
Thanks for the follow-up. This morning I traced this back to the Great Debian Node Renaming that now requires nodejs-legacy to be installed for some npm packages to properly install. The key feature was many ENOENT (mid-work files missing) during the install process.

**Comment by pkra** [comment]
Glad to hear you could resolve it. I've had trouble with the various ppa's as well; you might want to check out nvm and n for managing nodejs/iojs versions.
