### ISSUE TITLE
integrate CommonHTML

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#111]
With MathJax v2.6 we want to enable Mathjax-node to use the CommonHTML and FastHTML output.

**Comment by dpvc** [comment]
I've completed the work for CommonHTML with pull request #161.  I don't plan to add PreviewHTML (old FastHTML), since CommonHTML is better, and PreviewHTML was never intended for final output.  Do you see a need for PreviewHTML?

**Comment by pkra** [comment]
> Do you see a need for PreviewHTML?

Not very important to me. I know some people like its TimesNewRoman look and it's relatively small in terms of resulting markup. But let's separate it out and see if there's interest.

**Comment by pkra** [comment]
Separate out the FastHTML in #163

**Comment by pkra** [comment]
Fixed by #161
