### ISSUE TITLE
renaming the package

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#113]
npm forces new packages to only use lower case. Should we rename MathJax-node to mathjax-node in package.json?

**Comment by pkra** [comment]
Reference: https://docs.npmjs.com/files/package.json

**Comment by dpvc** [comment]
Sounds like we will have to make the change, so I guess there isn't any real option..

**Comment by pkra** [comment]
This has been fixed in v0.4.0

**Comment by spelufo** [comment]
The README still says `npm install MathJax-node`, it should be fixed.
