### ISSUE TITLE
Using an html5 file with mml for conversion results in spaces between mml tags getting converted to "ampersand nbsp semicolon"

### ISSUE THREAD

**Issue by nirupa-kumar** [mathjax/MathJax-node#118]
When submitting an html5 file that contains multiple equations using mml , the space between text and mml tags gets converted to the html code for a space "ampersand nbsp semicolon" This is seen in the Speak Text , i.e. the description. This does not happen if it is a single equation and occurs only in case of a html5 file.
Please let me know if you need any further information or if this needs to be assigned to speech-rule-engine. 
For example :
<xmp><mn>   5   </mn></xmp>

would get converted in description to "ampersand nbsp semicolon 5 ampersand nbsp semicolon"

**Comment by pkra** [comment]
I'm not 100% sure what you are describing both in terms of input and output.

I'm guessing you're doing something similar to running `node bin/page2svg --speech  < mml.html > mml2.html` for some example HTML. 

I'm not sure where you are seeing `&nbsp;`'s in the output.

E.g., using something like 

```html

<!doctype html>
<html lang=en>
<meta charset=utf-8>
<title>mml</title>
<math>
  <mi>a</mi><mo>&#x2260;</mo><mn> 0 </mn>
</math>
```

produces output with description `a not-equals 0` in its output. Even adding `&nbsp;`s around 0 does not change the output.

I suspect those `&nbsp;`s are added in other parts of your processing pipeline.

**Comment by nirupa-kumar** [comment]
page2svg works fine. page2mml does not. That's the one I am having an issue with. Please let me know if you are still not able to reproduce it. Thanks for responding so quickly.

**Comment by dpvc** [comment]
I also can't reproduce your results.  I used the test file

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset=utf-8>
  <title>mml</title>
</head>
<body>
  <math>
    <mi>a</mi><mo>&#x2260;</mo><mn> 0 </mn>
  </math>
  and
  <math>
    <mi>a</mi><mo>&#x2260;</mo><mn> 0 </mn>
  </math>
</body>
</html>
```

which fixes some HTML problems with Peter's example and also include more than one equation, as  you indicate is needed.  But `page2mml` produces

```
<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<title>mml</title>
</head>
<body>
<math xmlns="http://www.w3.org/1998/Math/MathML" alttext="a not-equals 0"><mi>a</mi><mo>≠</mo><mn>0</mn></math>
and
<math xmlns="http://www.w3.org/1998/Math/MathML" alttext="a not-equals 0"><mi>a</mi><mo>≠</mo><mn>0</mn></math>

</body></html>
```

for me.  There does not seem to be any issue with the spaces.

On the other hand, if the spaces are actually non-breaking spaces to start with, as in 

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset=utf-8>
  <title>mml</title>
</head>
<body>
  <math>
    <mi>a</mi><mo>&#x2260;</mo><mn>&nbsp;0&nbsp;</mn>
  </math>
  and
  <math>
    <mi>a</mi><mo>&#x2260;</mo><mn>&nbsp;0&nbsp;</mn>
  </math>
</body>
</html>
```

then I do see error messages about un recognized entity nbsp and the resulting speech string does include `ampersand n b s p semicolon`.

I tracked that down to the `AdjustMML()` function, which adds the speech text to the MathML output.  Apparently `math.outerHTML` converts literal U+00A0 characters to the entity `&nbsp;`, and the speech rule engine doesn't handle that.  I think it would probably be best of the SRE would process that, but it is also possible to modify [`AdjustMML()` function](https://github.com/mathjax/MathJax-node/blob/master/lib/mj-page.js#L646) to be

```
function AdjustMML() {
  if (data.renderer === "NativeMML") {
    var nodes = document.getElementsByClassName("MathJax_MathML");
    for (var i = nodes.length-1; i >= 0; i--) {
      var math = nodes[i].getElementsByTagName("math")[0]
      nodes[i].parentNode.replaceChild(math,nodes[i]);
      var alttext = speech.processExpression(math.outerHTML.replace(/&nbsp;/g,"\u00A0"));
      if (data.speakText) math.setAttribute("alttext",alttext);
    }
  }
}
```

to convert the `&nbsp;` back to literal U+00A0 for now.

**Comment by nirupa-kumar** [comment]
@dpvc - Thank you. I will make sure I am more clearer in the details next time around. I will go ahead and raise the issue with SRE.
