### ISSUE TITLE
Integrate AssistiveMML extension

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#119]
Just a note for 2.6 integration.

**Comment by pkra** [comment]
This should probably just be a code snippet in some kind of documentation?

**Comment by pkra** [comment]
Here's an example https://github.com/mathjax/MathJax-node/wiki/A-sample-recipe

**Comment by pkra** [comment]
@dpvc @zorkow any objections to rejecting this? Seems odd to me to have add this now.

**Comment by dpvc** [comment]
Agreed.  It is no longer pertinent.
