### ISSUE TITLE
NodeJS 4 compatibility

### ISSUE THREAD

**Issue by Rycochet** [mathjax/MathJax-node#122]
The required changes are in the develop branch, but until it's merged into master I don't think anyone can actually use this in a node project due to node-gyp failures on it (and even when node-gyp finish sorting things out there'd still be the locked jsdom dependency version for the current npm release)...

Just hoping this is a reminder for that, and let people who need it watch for the update being released :-)

Manual install (ie, bypassing ```npm install``` from package.json):
```
npm install github:mathjax/MathJax-node#develop
```

**Comment by episodeyang** [comment]
yeah, I'm like "come on"..... just ran into the same problem.

**Comment by pkra** [comment]
This has been fixed in v0.4.0

**Comment by Rycochet** [comment]
Nice - but there's now two versions on npmjs - note the camel case of the out of date one -

https://www.npmjs.com/package/MathJax-node - 0.3.0
https://www.npmjs.com/package/mathjax-node - 0.4.0

Not sure if that one can be removed (to match the full lower-case mathjax etc), or both kept up to date?

**Comment by pkra** [comment]
Yes, that was inevitable for the name change.

For now, the old package has been marked as deprecated which means you will
get a warning when installing it, with a custom message pointing to the new
name.

Eventually, this old one will be removed.

**Comment by Rycochet** [comment]
I'm going to hope that people find this issue if it comes up, but hopefully they're smart enough to just change the case in their package.json file and update - they'd hopefully be changing the version required at the same time ;-)

**Comment by pkra** [comment]
Well,

```bash
$ npm install MathJax-node
```

Will result in something like

```bash
npm WARN deprecated MathJax-node@0.3.0: WARNING: This project has been renamed to mathjax-node. Install using mathjax-node instead.
```

So hopefully, they will not need to find this issue.

**Comment by Rycochet** [comment]
It's more to do with ```npm update``` not finding an updated version and simply erroring out because it's trying to use the old jsdom - so any warning that might be there won't get seen behind all the red ;-)
