### ISSUE TITLE
can not find module with node 0.12.7 and npm 3.3.7

### ISSUE THREAD

**Issue by episodeyang** [mathjax/MathJax-node#123]
Hi,

I am encountering the following error after upgrading to node 0.12.7

I have been trying to figure this one out for a while. All of my other modules register correctly except Mathjax-node. Any idea?

![screenshot 2015-10-09 00 09 12](https://cloud.githubusercontent.com/assets/630490/10386232/062d9acc-6e1a-11e5-8e38-ff3e28412a8b.png)

**Comment by episodeyang** [comment]
Hi @dpvc 

Would you mind check this out? I'm at my wit's end.

Will come back to spend more time tomorrow.

**Comment by pkra** [comment]
I'm afraid you cannot require MathJax-node at this point but only mj-single and mj-page. We're hoping to address this after MathJax v2.6 is out.

**Comment by episodeyang** [comment]
Thanks Peter, what do you mean by this? are mj-single and mj-page callable this way?

```javascript
var mj-single = require('mj-single')
```

**Comment by pkra** [comment]
You need something like

   var mjAPI = require("MathJax-node/lib/mj-single");
