### ISSUE TITLE
How to configure the font size of generated math PNGs

### ISSUE THREAD

**Issue by mrueegg** [mathjax/MathJax-node#127]
Hi,

Is there any way to configure the font size of the resulting math expressions when using PNG as output format?

Thanks,
Michael

**Comment by dpvc** [comment]
If you are using the command-line tools, there are two options that can be used to control the PNG image size:  `--ex` and `--dpi`.  The `--ex` option specifies the font's ex-height in pixels.  The default is 6, so making that larger should enlarge the image.  Alternatively, you can set `--dpi` which can be used to increase the resolution.  Either of those should do what you need, I think.

**Comment by mrueegg** [comment]
Thanks for your reply. I've already played around with both --ex and --dpi, but didn't get the results I was looking for. I have to generate inline math expressions as PNG images which should line up and be more or less the same size as the surrounding text (11pt times font). The generated math PNG's were also way too large with the chosen arguments for tex2png.

Do you have any idea how I can generate expressions that are the same size as a 11pt times font?

**Comment by dpvc** [comment]
When I use `tex2png 'x' > x.png` and then view the size, it is an 8x10 pixel image, which is an appropriate size for use with 11pt times.  What sized image do you get?

**Comment by mrueegg** [comment]
Thanks, you are right. 

One more question: do you know how I can specify a maximum height for the math expressions when generating a PNG? My PNG is used by a framework which scales the PNG to a minimum height. So it heavily depends on the size of the math expressions if the math looks fine or gets blurred. See as an example the attached images. The grey area is the bounding box the framework uses to show my generated PNGs. With 150 DPI, the math looks fine, but is way to large for an inline text:

![150dpi](https://cloud.githubusercontent.com/assets/206944/10723520/e06569fa-7bbb-11e5-98cd-4eabe16c98dc.png)

With 75 DPI, the size would be okay, but for smaller expressions like "E = mc^2", it gets stretched and blurred:

![75dpi](https://cloud.githubusercontent.com/assets/206944/10723518/e05e1bb4-7bbb-11e5-98ac-ecf677391975.png)

I would like to specify a maximum height for the generated PNG so that it has a margin like shown in the last picture and hence doesn't get stretched:

![with_margin](https://cloud.githubusercontent.com/assets/206944/10723519/e05eec56-7bbb-11e5-9993-6b273d0fcd79.png)

Is that possible?

**Comment by pkra** [comment]
> would like to specify a maximum height for the generated PNG so that it has a margin like shown in the last picture and hence doesn't get stretched

There is no built-in way of doing this. This would involve processing entire pages, tracking the heights of each equation and adding the specific offset needed; that's a somewhat strange use case and will depend heavily on the exact behavior of the framework.

Not that it helps but FWIW if you use MathJax-node to process entire pages (e.g., using `page2png`), it would correctly size and align the equations (in particular baselines). This would not eliminate different heights, obviously.

**Comment by mrueegg** [comment]
Thanks a lot for your feedback.

**Comment by pkra** [comment]
Of course, I might be wrong and the specifics of the framework can easily be resolved; hard to tell without more details.
