### ISSUE TITLE
Update MathJax dependency

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#133]
We should update to 2.5.2 or jump straight to 2.6.0.

Cf. https://github.com/mathjax/MathJax-node/pull/132

**Comment by physikerwelt** [comment]
It's however not that urgent since I found a workaround
https://github.com/physikerwelt/MathJax-node/commit/c4770d8978630898e10839134f29a4c42851704e
so mathoid is not completly stuck after hitting this bug

**Comment by pkra** [comment]
Glad to hear that. We're working hard on finalizing 2.6.

**Comment by physikerwelt** [comment]
see also also https://phabricator.wikimedia.org/T121762

**Comment by pkra** [comment]
This was resolved in #160.
