### ISSUE TITLE
change README to show the code as people would use it?

### ISSUE THREAD

**Issue by Pomax** [mathjax/MathJax-node#136]
Right now the README.md shows a use of `require` that references local files, rather than files that are part of the module: `require("./lib/mj-page.js");`. This implies someone has to manually copy the `mj-page.js` file to their local `lib` dir, whereas these files are already part of the module's payload and can simply be required the normal way. It would be better to change this to `require("MathJax-node/lib/mj-page.js");` since that is how people will have received the mathjax-node package.

Although related to that, it's worth renaming the package for the next release to all-lowercase, to prevent possible problems with case sensitive operating systems (and a trivial refactor for users, since virtually all code editors come with a "replace in all files" function)

**Comment by pkra** [comment]
> . It would be better to change this to require("MathJax-node/lib/mj-page.js"); since that is how people will have received the mathjax-node package.

Good point.

>  it's worth renaming the package for the next release to all-lowercase,

That's already the case.

**Comment by pkra** [comment]
This was fixed in #137
