### ISSUE TITLE
synchronous path

### ISSUE THREAD

**Issue by Pomax** [mathjax/MathJax-node#140]
For the purpose of static page generation and unit testing, it would be invaluable to have a synchronous function available, rather than only having a callback available. E.g. something like:

```
var mathjax = require("mathjax-node/lib/mj-single");
mathjax.config({
  ...
});

...

function renderToString(latexCode) {
  return mathjax.render(latexCode);
}

...
```

**Comment by dpvc** [comment]
Unfortunately, that is not possible with the current MathJax architecture, as that code is not atomic (i.e., it may have to wait for files to load), and so the `mathjax.render()` function you suggest is not currently possible without a lot of restructuring of MathJax's internals.  That is not currently planned.

**Comment by pkra** [comment]
Closing this here. MathJax v3 is synchronous and will subsume mathjax-node; cf.  #375.
