### ISSUE TITLE
HTML+CSS rather than MML or SVG?

### ISSUE THREAD

**Issue by Pomax** [mathjax/MathJax-node#142]
Regular MathJax has the `TeX-AMS_HTML` config, for precision typesetting, which generates true HTML rather than MML (a [dead format](http://caniuse.com/#search=mathml) by now, at least if the intention is to use the material in a web browser) or SVG (which doesn't looks as crisp at the low point sizes used on the web due to SVG not having any hinting instructions for pixel-aligning letterform, compared to real text typeset with OpenType fonts)

Is there a way to make the mathjax-node library generate the HTML output? Looking at the bin dir, I only see mml, svg, and png converters... there is an `mml2svg-html5`, but that only converts MML to SVG.

**Comment by pkra** [comment]
> Is there a way to make the mathjax-node library generate the HTML output?

Yes, very soon. See https://github.com/mathjax/MathJax-node/issues/111

**Comment by Pomax** [comment]
Nice! Although there are no PRs crosslinked, so it looks like that's still in the "we want to do this" rather than "we're releasing this soon" stage?

**Comment by pkra** [comment]
There's already a branch here (but some jsdom bugs need fixing). And 2.6 is about to be finalized.

**Comment by Pomax** [comment]
Hurray - I'm currently rewriting pomax.github.io/bezierinfo to be more responsive, for which offline conversion is going to be crucial (currently looking at just having Phantomjs or Casperjs actually generate with plain MathJax, and then grabbing the resulting generated code. Extremely far from ideal, but it does mean being able to take advantage of all of MathJax's capabilities)

**Comment by dpvc** [comment]
Note that the current HTML-CSS output is browser and platform dependent, so is not appropriate for pre-rendering (the results need to be different for different browsers on different OSes with different fonts installed at different zoom levels, etc).

The new CommonHTML output is designed to be the same for all browsers and OSes, and being able to pre-render the expressions was one of the design goals.  As Peter says, that is the next step (once we can fix some jsdom issues) after the 2.6 release that was just made yesterday.

**Comment by Pomax** [comment]
Happy to hear about the CommonHTML format.

**Comment by pkra** [comment]
This was a duplicate.
