### ISSUE TITLE
Not a bug, but perhaps nice to know about - using mathjax-node in the wild.

### ISSUE THREAD

**Issue by Pomax** [mathjax/MathJax-node#146]
I know I've been filing a fair number of issues here in the last few days (and thanks so much for all the great help!), and I figured it'd be nice to explain what I'm actually doing =)

I run https://pomax.github.io/bezierinfo, an online book on Bezier curves, and it heavily relies on MathJax. However, it also takes forever to load, so I finally sat down to rewrite it from purely static HTML with client-side rendering to a React app that gets pregenerated so that client-side nothing significant needs to happen anymore, including prerendering all the LaTeX.

Thanks to your help, the result is really nice at this point (https://pomax.github.io/BezierInfo-2, still in the process of porting all sections), and because I had to marry Webpack's purely sync processing to mathjax-node's asynchronous processing, there's some magic to make everything work that I documented over on http://pomax.github.io/1451617530567/react-with-latex-without-needing-client-side-mathjax

So hopefully that's something you find interesting, and with that: happy new year and thanks for all the help!

**Comment by pkra** [comment]
Thanks for sharing this, @Pomax!
