### ISSUE TITLE
Error: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by johnnygames** [mathjax/MathJax-node#150]
Hello, I'm trying to use this library to parse chunks of HTML using `mj-page`. I have this function,

```
function startMathJax(){
  var mjAPI = require("MathJax-node/lib/mj-page");
  mjAPI.config({
    MathJax: {
      tex2jax: {
        processEscapes: true,
        inlineMath: [ ['$','$'], ["\\(","\\)"] ]
      },
    }
  });
  mjAPI.start();
  return mjAPI;
}
```

executing when my server spins up and pass it data use `jsdom`, similar to the example in the readme. When my server spins up I get the message `Error: Cannot read property 'replace' of undefined` and Mathjax does nothing when I try to use it. I'm using node v4.2.3 and MathJax-node v0.4.0. 

The error appears to occur during initialization, but I can't pinpoint where or why.

**Comment by johnnygames** [comment]
Ah, it appears the error was due to using `.config` before using `.start()`. My fault!

**Comment by pkra** [comment]
Thanks for the update.
