### ISSUE TITLE
travis: which node versions to test?

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#153]
Given https://github.com/mathjax/MathJax-node/commit/93ae1a8c834fbab9fa9ac59b7745561ac97e437c#commitcomment-15888948, should we add more versions than `stable`?

**Comment by dpvc** [comment]
I don't think is should be necessary, in general.  That particular problem is not likely to occur again (it was in the code that I added to patch jsdom until the CSS fixes that I submitted make it into the release version of jsdom).  It is pretty low-level and susceptible to the kinds of changes that occurred from node4 to node5, but the rest of MathJax-node doesn't do that sort of thing, and is pretty generic in terms of its use of node.  Do you think there will be many more breaking changes for node?

**Comment by pkra** [comment]
> Do you think there will be many more breaking changes for node?

Chances are that there will be. Not necessarily node but, e.g., I just ran into a case where npm on Node 5 breaks something.

Since Node now officially makes [long-term-support releases](https://github.com/nodejs/LTS#lts_schedule), how about we support those starting with node 4.2.x?

**Comment by dpvc** [comment]
OK, go for it.

**Comment by pkra** [comment]
copy that.

**Comment by pkra** [comment]
Fixed by #155
