### ISSUE TITLE
package.json default

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#162]
I have a question. 

[Currently](https://github.com/mathjax/MathJax-node/blob/master/package.json#L33), `mj-page` is the default. I was wondering if mj-single is not the more commonly used one (as long as we don't have a single solution). 

Any thoughts?

**Comment by dpvc** [comment]
Fine by me if you want to change it.  You are probably right that it is being used with `mj-single` more often.

**Comment by pkra** [comment]
Great. @zorkow ?

**Comment by pkra** [comment]
https://github.com/mathjax/MathJax-node/pull/167

**Comment by dpvc** [comment]
Are we waiting on Volker before merging?

**Comment by pkra** [comment]
I was hoping to do this unanimously. He'll be at the department today though.

**Comment by pkra** [comment]
This was resolved by #167
