### ISSUE TITLE
integrate PreviewHTML

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#163]
[This has been separated from #111. ]

If there is sufficient interest, we could enable the PreviewHTML in MathJax-node.

The PreviewHTML an HTML/CSS output that's lower-quality (both in terms of supported constructions and quality) than the CommonHTML; it's basically the old version of the CommonHTML from MathJax v2.5.  

The advantages would be smaller HTML fragment size, the fact that it is optimized for TimesNewRoman or similar local fonts (i.e., no webfonts) and rendering speed.

**Comment by dpvc** [comment]
It is not feature complete, however, so some things don't render.  E.g., menclose is not implemented, and I think horizontal stretchy characters may not be, and the spacing can be a bit wonky.

**Comment by pkra** [comment]
Cleaning up my old issues.
