### ISSUE TITLE
Strange unicode bug (probably)

### ISSUE THREAD

**Issue by ischurov** [mathjax/MathJax-node#169]
I'm testing develop branch and found the following problem.

I have a [file](https://gist.githubusercontent.com/ischurov/2f1089b564d21ab2fa77/raw/489a59abaf2f0463df82b35f7ad0349aed06c1fa/testcase-mathjax-node-ee.html) which I want to convert to HTML-CSS with `page2html`. When I do it from the command line, like

    ./page2html < testcase-mathjax-node-ee.html > out.html

everything goes fine.

However, when I try to do it from Python script (which I need), one of cyrillic letter `е` is replaced with a couple of unreadable unicode symbols.

The script follows:
```python
from subprocess import Popen, PIPE
with open("testcase-mathjax-node-ee.html") as f:
    s = f.read()

p = Popen(['./page2html'], stdout=PIPE, stdin=PIPE, stderr=PIPE)

res = p.communicate(input=s.encode('utf-8'))
out = res[0].decode('utf-8')
err = res[1].decode('utf-8')
print(out)
```

Then `python3 test.py | grep "Получим"` will give me the following output:

```
<…> Получим следующе�� уравнение:
```

Note the characters at the end of the line.

The problem disappears if I change anything in the file (e.g. delete first line or add a character).

Problem reproduces on `page2xml`.

I'm a bit not sure, if it is correct place to file this bug, because I don't know how to reproduce this bug without Python. However, my first guess is that something can be wrong with UTF-8 processing inside Mathjax-Node (or underliying libraries)

**Comment by pkra** [comment]
>  I don't know how to reproduce this bug without Python. However, my first guess is that something can be wrong with UTF-8 processing inside Mathjax-Node (or underliying libraries)

It seems to me the first investigation should be about Python?

Anyway, I can't reproduce this issue using Python 3.5.

**Comment by ischurov** [comment]
Okay, now I tried to reproduce it on Linux box (instead of Mac OS X), but failed either. Seem to be Python/OSX-related issue, I'll try to investigate it further.

BTW, it does not depend on Node.js version (reproduced under Mac OS X with Node.js 5.6.0 and Node 4.2.1).

**Comment by pkra** [comment]
> Okay, now I tried to reproduce it on Linux box (instead of Mac OS X), but failed either.

Just to double check: did you or did you not see the bug on Linux?

**Comment by ischurov** [comment]
I do not see the bug on Linux.

**Comment by pkra** [comment]
Thanks, @ischurov. Let us know if we can do anything else to help.
