### ISSUE TITLE
Prevent the `color` extension from auto-loading

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#175]
From https://github.com/mathjax/MathJax-node/issues/143#issuecomment-168243285.

> You are right to point out the `autoload-all` extension, and I was going to say that because `\color` is already defined in MathJax's TeX input jax by default, that `autoload-all` would not redefine it, but I checked the code and I am wrong; `\color` is set to autoload the color extension.  I'm not sure that is the desired behavior for MathJax-node, since that means it will operate differently from default MathJax in the browser.

**Comment by pkra** [comment]
Question: Do we want to drop the autoload extension entirely or do we want to load all extensions except the color extension?

**Comment by dpvc** [comment]
I think it is OK to use `autoload-all`, but perhaps we should put back the original definition for `color` once it loads.  That would be easy enough to add.

**Comment by pkra** [comment]
> I think it is OK to use autoload-all, but perhaps we should put back the original definition for color once it loads. That would be easy enough to add.

Do you mean just copy&paste https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/TeX/jax.js#L1320-L1326?

**Comment by pkra** [comment]
In other words: I don't think I know how to fix this :frowning_face:

**Comment by dpvc** [comment]
You should add

```
      if (MathJax.AuthorConfig.extensions.indexOf("TeX/color.js") == -1) {
        MathJax.Hub.Register.StartupHook("TeX autoload-all Ready",function () {
          var macros = MathJax.InputJax.TeX.Definitions.macros;
          macros.color = "Color";
          delete macros.textcolor;
          delete macros.colorbox;
          delete macros.fcolorbox;
          delete macros.definecolor;
        });
      }
```

at line 425 of `main.js` to get back the original `\color` functionality.  One can then use the `--extensions "TeX/color"` option to force the LaTeX-compatible color functions.
