### ISSUE TITLE
Prevent TEX.resetEquationNumbers if the AMSmath extension is not loaded

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#176]
From https://github.com/mathjax/MathJax-node/issues/143#issuecomment-168243285.

> So in particular the `AMSmath` extension was no longer loaded, and that is the one that defines the `TeX.resetEquationNumbers()` method.  I suppose MathJax-node should be modified to avoid calling that if it doesn't exist.

**Comment by pkra** [comment]
@dpvc will this be fixed by https://github.com/mathjax/MathJax/pull/1464/, right?

**Comment by dpvc** [comment]
Yes, that should do it.

**Comment by pkra** [comment]
Ok. Removing this from the milestone and marking it upstream.

**Comment by pkra** [comment]
Now that MathJax has hit 2.7-beta (and includes the fix), I think we can close this.
