### ISSUE TITLE
page2html rewrites self-closing tags

### ISSUE THREAD

**Issue by a3nm** [mathjax/MathJax-node#180]
Consider the following HTML document:

```
<!DOCTYPE html>
<html dir="ltr" xml:lang="en-US" lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>blah</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  </head>
  <body>
  </body>
</html>
```

When piping it to page2html, the following output is produced:

```
<!DOCTYPE html>
<html dir="ltr" xml:lang="en-US" lang="en-US" xmlns="http://www.w3.org/1999/xhtml"><head>
    <title>blah</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
  <style id="MathJax_CHTML_styles">undefined</style></head>
  <body>
  


</body></html>
```

I don't like the fact that the self-closing tag `meta` tag was rewritten to omit the ending '/', as I am trying to produce HTML which is also valid XML. I think it would be better if page2html left self-closing tags as is, at least on parts of the HTML that it does not touch.

**Comment by pkra** [comment]
This is an upstream issue of jsdom. However, they might not change the behavior as this is what some browser (in particular webkit based browsers) do with this example when loaded as HTML (then again, Gecko/Firefox does a better job so you could make a case for that upstream).

In the mean time, you could try loading the file as XML, e.g., by setting `config.parsingMode` in jsdom.

**Comment by a3nm** [comment]
Thanks for the explanation. My issue with the self-closing tags was about picky validation tools, but I think I'll probably just make them less picky and give up on XML compliance. Anyway, thanks for clarifying! :)

**Comment by pkra** [comment]
Thanks for the follow up -- always appreciated.
