### ISSUE TITLE
Add speech output to CommonHTML output

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#189]
We should add the speech output to the HTML output if requested.

**Comment by pkra** [comment]
Note: we should probably remove `role=math` since this trips up most ATs and adds nothing, really.

**Comment by dpvc** [comment]
I think that is probably an upstream request, since I think it is the output jax that add that.

**Comment by pkra** [comment]
> I think that is probably an upstream request, since I think it is the output jax that add that.

Fair point (this is about `role=math`, right?).

**Comment by dpvc** [comment]
> this is about `role=math`, right?

Yes.

**Comment by pkra** [comment]
I've created https://github.com/mathjax/MathJax/issues/1437 for the problem of role=math.

**Comment by pkra** [comment]
=> merged
