### ISSUE TITLE
unicode symbol x2206 in mathML not being output in SVG

### ISSUE THREAD

**Issue by corinnaSchultz** [mathjax/MathJax-node#196]
This should be the increment (delta) symbol. I tried the hex entity as well as the decimal equivalent (8710) in the mathML, and got the same output result. 

Input mathML:

     <math xmlns="http://www.w3.org/2010/Math/MathML"><semantics><mstyle scriptsizemultiplier="0.715"><mo>&#x2206;</mo></mstyle><annotation encoding="text/plain"></annotation></semantics></math>

output SVG:

     <svg xmlns:xlink="http://www.w3.org/1999/xlink" style="vertical-align: -0.338ex;" width="1.936ex" height="2.176ex" viewBox="0 -791.3 833.5 936.9" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg">\n<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)">\n<path stroke-width="1" d=""></path>\n</g>\n</svg>

**Comment by dpvc** [comment]
It looks like the SVG font data for `&#x2206;` is incorrect.  I'll see what I can do about it.

**Comment by pkra** [comment]
Marked as upstream.

**Comment by pkra** [comment]
Now that MathJax has hit 2.7-beta (and includes the fix), I think we can close this.
