### ISSUE TITLE
Install bin to path

### ISSUE THREAD

**Issue by mlucool** [mathjax/MathJax-node#198]
Hi,

Is it intentional not to install all the bins to the PATH when installed globally? i.e.: https://docs.npmjs.com/files/package.json#bin

Thanks,
Marc

**Comment by pkra** [comment]
> Is it intentional not to install all the bins to the PATH when installed globally?

No. However, we've been discussing moving the files in the `bin` folder elsewhere (i.e., out of this package).

**Comment by mlucool** [comment]
Do you have a link to the request for moving the files? I can make the PR for this either way

**Comment by pkra** [comment]
> Do you have a link to the request for moving the files? 

I'm afraid not. As I wrote, this is only being discussed so far.

**Comment by pkra** [comment]
> Do you have a link to the request for moving the files?

See #208

**Comment by pkra** [comment]
Closing given the resolution of #208 / https://github.com/mathjax/mathjax-node-cli
