### ISSUE TITLE
mathML beveled fraction not rendered in SVG when following <mn> tag

### ISSUE THREAD

**Issue by corinnaSchultz** [mathjax/MathJax-node#201]
-If I put a number before the fraction, only the number will be rendered. If the number is wrapped in its own mstyle tag, or if I remove the mstyle tag altogether, I get the same result, too.   I expect this to be valid mathML, and to render as expected. (Is this somehow not valid markup?)

     <math xmlns="http://www.w3.org/2010/Math/MathML"><semantics><mn>4</mn><mstyle displaystyle="false"><mfrac bevelled="true"><mn>1</mn><mn>2</mn></mfrac></mstyle><annotation encoding="text/plain"/></semantics></math>

<img width="28" alt="four" src="https://cloud.githubusercontent.com/assets/8988264/13969863/69995b5a-f042-11e5-8f72-653d307debfb.png">

SVG:

     <svg xmlns:xlink="http://www.w3.org/1999/xlink" style="vertical-align: -0.338ex;" width="1.162ex" height="2.176ex" viewBox="0 -791.3 500.5 936.9" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg">\n<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)">\n<path stroke-width="1" d="M462 0Q444 3 333 3Q217 3 199 0H190V46H221Q241 46 248 46T265 48T279 53T286 61Q287 63 287 115V165H28V211L179 442Q332 674 334 675Q336 677 355 677H373L379 671V211H471V165H379V114Q379 73 379 66T385 54Q393 47 442 46H471V0H462ZM293 211V545L74 212L183 211H293Z"></path>\n</g>\n</svg>

-If I have mathML that is simply a beveled fraction, it will render correctly.

mathml:

     <math xmlns="http://www.w3.org/2010/Math/MathML"><semantics><mstyle displaystyle="false"><mfrac bevelled="true"><mn>1</mn><mn>2</mn></mfrac></mstyle><annotation encoding="text/plain"/></semantics></math>

<img width="37" alt="half" src="https://cloud.githubusercontent.com/assets/8988264/13969819/3cf71f7e-f042-11e5-9cdd-45de385b3294.png">

SVG:

     <svg xmlns:xlink="http://www.w3.org/1999/xlink" style="vertical-align: -0.838ex;" width="3.015ex" height="2.843ex" viewBox="0 -863.1 1298.3 1223.9" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg">\n<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)">\n<g transform="translate(120,0)">\n<g transform="translate(0,164)">\n<path stroke-width="1" transform="scale(0.707)" d="M213 578L200 573Q186 568 160 563T102 556H83V602H102Q149 604 189 617T245 641T273 663Q275 666 285 666Q294 666 302 660V361L303 61Q310 54 315 52T339 48T401 46H427V0H416Q395 3 257 3Q121 3 100 0H88V46H114Q136 46 152 46T177 47T193 50T201 52T207 57T213 61V578Z"></path>\n</g>\n<path stroke-width="1" d="M423 750Q432 750 438 744T444 730Q444 725 271 248T92 -240Q85 -250 75 -250Q68 -250 62 -245T56 -231Q56 -221 230 257T407 740Q411 750 423 750Z" transform="translate(278,0)"></path>\n<g transform="translate(704,-136)">\n<path stroke-width="1" transform="scale(0.707)" d="M109 429Q82 429 66 447T50 491Q50 562 103 614T235 666Q326 666 387 610T449 465Q449 422 429 383T381 315T301 241Q265 210 201 149L142 93L218 92Q375 92 385 97Q392 99 409 186V189H449V186Q448 183 436 95T421 3V0H50V19V31Q50 38 56 46T86 81Q115 113 136 137Q145 147 170 174T204 211T233 244T261 278T284 308T305 340T320 369T333 401T340 431T343 464Q343 527 309 573T212 619Q179 619 154 602T119 569T109 550Q109 549 114 549Q132 549 151 535T170 489Q170 464 154 447T109 429Z"></path>\n</g>\n</g>\n</g>\n</svg>

-If the number is a child of the same mstyle tag, then it renders correctly.

     <math xmlns="http://www.w3.org/2010/Math/MathML"><semantics><mstyle displaystyle="false"><mn>4</mn><mfrac bevelled="true"><mn>1</mn><mn>2</mn></mfrac></mstyle><annotation encoding="text/plain"/></semantics></math>

<img width="45" alt="fraction" src="https://cloud.githubusercontent.com/assets/8988264/13970184/716799bc-f044-11e5-9ad4-de51489b3c95.png">

-If I wrap both parts of the expression (the number and the fraction) in an mrow tag then it also renders correctly.

     <math xmlns="http://www.w3.org/2010/Math/MathML"><semantics><mrow><mn>4</mn><mstyle displaystyle="false"><mfrac bevelled="true"><mn>1</mn><mn>2</mn></mfrac></mstyle></mrow><annotation encoding="text/plain"/></semantics></math>

**Comment by dpvc** [comment]
The MathML is incorrect.  The `<semantics>` element is supposed to have its first child be the MathML that is rendered, and all the other elements are supposed to be `<annotation>` or `<annotation-xml>` nodes.  Your first example has `<mn>4</mn>` as the first child, so that is all that is rendered.  When you put the number and fraction inside an `<mstyle>` or an `<mrow>`, then that container becomes the first child, and its contents is rendered.  Without this, the `<semantics>` element is invalid, since the second child is an `<mfrac>` rather than an `<annotation>` or `<annotation-xml>` node.

So this is expected behavior and consistent with the spec.
