### ISSUE TITLE
move SRE integration out of mj-node

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#207]
As per F2F (cf. #191), the SRE integration will be moved out of mathjax-node; there will be alternative modules.

**Comment by zorkow** [comment]
Just started looking into this. I assume it's best tackled after PR #247 is merged.

**Comment by pkra** [comment]
I agree -- best to wait until #247.

**Comment by pkra** [comment]
From F2F, we should preserve the code in mj-single to add dummy speech text (e.g., TeX/asciimath source); this will be helpful for post-processing, in particular for the SVG infrastructure of labeledby/title (running IDs etc).

**Comment by pkra** [comment]
Merged into `develop`.
