### ISSUE TITLE
simplifying MathJaxPath

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#212]
If https://github.com/mathjax/MathJax/issues/1442 happens, then we should be able to simplify https://github.com/mathjax/MathJax-node/blob/master/lib/mj-single.js#L87 to require('mathjax').

**Comment by pkra** [comment]
I meant require.resolve()

**Comment by pkra** [comment]
https://github.com/mathjax/MathJax/issues/1442 did happen. But we'll have to wait until the next upstream release later this summer.

**Comment by devnullnor** [comment]
This library gets an error when running on Azure.
`Can't load MathJax.js from file://<myaipaddress>/volume-15-default/752e966e0608c78090be/6baa65c680e84188abd6785084571608/site/wwwroot/node_modules/mathjax/unpacked/MathJax.js`

A temporary fix is: `MathJaxPath = '/home/site/wwwroot/node_modules/mathjax/unpacked/MathJax.js';`

**Comment by pkra** [comment]
@devnullnor thanks for the feedback. Once there's a PR to resolve this, it would be great if you have the time to test it out on Azure.

**Comment by devnullnor** [comment]
I will gladly test it.

**Comment by pkra** [comment]
@devnullnor could you test out #267? Besides the minimal change on that branch, you'll need to manually `npm install mathjax@v2.7.0.-beta.0` (though 2.7 should go out this week).
