### ISSUE TITLE
Two different packages on npm

### ISSUE THREAD

**Issue by jhiesey** [mathjax/MathJax-node#214]
I first found https://www.npmjs.com/package/MathJax-node on npm, which appears to be an old version. The current version looks to be https://www.npmjs.com/package/mathjax-node, which differs only by case.

I can't imagine I'm the only one who's downloaded the wrong version. Could you at least publish an update the README on the old one to point people to the new one?

**Comment by pkra** [comment]
If you install `MathJax-node` NPM should trigger a deprecation warning that reads: 

"npm WARN deprecated MathJax-node@0.3.0: WARNING: This project has been renamed to mathjax-node. Install using mathjax-node instead."

We thought that would be sufficient.

Personally, I don't mind one way or another if we add more information somewhere; @dpvc, @zorkow thoughts?

**Comment by dpvc** [comment]
I suppose changing the README so that the page at https://www.npmjs.com/package/MathJax-node indicates the change would be a reasonable thing to do.  Can that be done without screwing up the new package?

**Comment by pkra** [comment]
> I suppose changing the README so that the page at https://www.npmjs.com/package/MathJax-node indicates the change would be a reasonable thing to do.

No objection here.

> Can that be done without screwing up the new package?

Yes. We only publish tags (and as long as we don't change the version number in package.json, publishing to npm would fail without damaging the current version on npm).

**Comment by pkra** [comment]
On second read, I misunderstood you @dpvc. To change the readme on npm we would have to make a new NPM release with the old package name and a new version number in the package.json. That would have to be done manually, I think.

**Comment by pkra** [comment]
This would be my preferred solution: https://github.com/npm/newww/issues/413

**Comment by dpvc** [comment]
> That would have to be done manually, I think.

If we made a branch off the current 0.3.0 tag and changed the README.md and package.json in that branch and then tagged it 0.3.1, would we be able to publish that on npm for MathJax-node without screwing up mathjax-node?  If so, I'm OK with doing that.

Waiting for npm to make their changes is also fine with me.

**Comment by pkra** [comment]
> If we made a branch off the current 0.3.0 tag and changed the README.md and package.json in that branch and then tagged it 0.3.1, would we be able to publish that on npm for MathJax-node without screwing up mathjax-node? If so, I'm OK with doing that.

I don't know but I'm guessing it shouldn't cause any issues. Will do some research.

**Comment by pkra** [comment]
Fixed.
