### ISSUE TITLE
[mj-single] The HTML output should not include id attributes

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax-node#215]
The HTML output should probably have its id's removed (those that were added by the CommonHTML output).  Otherwise, we will end up with duplicate id's if the output from two conversions are included in the same page.

Also, the CHTML id's may want to be reset every typeset so that (if used as the backend of some other service) the id's don't grow unbounded.

Also, the `-Frame` element could be removed, as it is for the other output formats.

**Comment by pkra** [comment]
> The HTML output should probably have its id's removed

I was just running into this; I'll make a PR.

> the CHTML id's may want to be reset every typeset

Is that just adding `CHTML.SUPER.ID` to https://github.com/mathjax/MathJax-node/blob/develop/lib/mj-single.js#L762 ? 

> Also, the -Frame element could be removed, as it is for the other output formats.

Note to self: in display mode, the `-Frame` element is wrapped in `<span class="mjx-chtml MJXc-display" style="text-align: center;">` which should be preserved.

**Comment by pkra** [comment]
> is that just adding CHTML.SUPER.ID [...]

Apparently not. Would you have a pointer for me?

**Comment by dpvc** [comment]
> Is that just adding `CHTML.SUPER.ID`

Pretty close.  But `CHTML` is not defined in that routine, so you need to use the full reference to the CommonHTML output jax.  And the `SUPER` isn't needed for the output jax.  So something like

```
MathJax.OutputJax.CommonHTML.ID = 0;
```

should do (untested).  I think `CommonHTML` should always be defined, given the configuration, so I don't think you should have to test for that.

**Comment by pkra** [comment]
Thanks, I'll take a look.

**Comment by pkra** [comment]
I've split the reset into its own issue, #231.
