### ISSUE TITLE
[mj-page][HTML output] improve style handling

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#217]
A note for when we move mj-page out.

We might want to think about 
- adding the styles to the head (by default)
- expose the styles separately (like mj-single)

**Comment by dpvc** [comment]
Note that commands already exist for adding the styles to the head: `tex2htmlcss`, `mml2htmlcss`, and `am2htmlcss`  all produce complete HTML documents with the styles in place.

As for exposing the styles separately, that is already done via `tex2html --css ''`, `mml2html --css ''`, or `am2html --css ''`.

**Comment by pkra** [comment]
Closing this. See e.g. https://github.com/pkra/mathjax-node-page/issues/27 https://github.com/pkra/mathjax-node-page/issues/28
