### ISSUE TITLE
MathJax-node fails to report \c error

### ISSUE THREAD

**Issue by fptoth** [mathjax/MathJax-node#224]
Hi,

We use mathjax-node more for TeX error checking than rendering and we've run across this problem.

The following broken equation contains the string "\c" which is an error. This can be verified, for example, by pasting the equation into a MathJax test page.

`$$VBeBorn=reflexiveVP\ (P.dirV2(v\_besch106{\hbox{``}}na\c{s}te{\hbox{"}})).$$`

However, when running it through page2mml in mathjax-node, the error is not reported. Also, this MAY be related to ASCIIMath support, since when I turn off that extension, the error is reported correctly.

This is easy to reproduce:

- start with fresh install of mathjax-node
- save equation above to a file "test.html"
- run "node mathjax-node/bin/page2mml < test.html" (you will see mml output and no error).
- make a modification to lib/mj-page.js:

Comment out line 652 (//AsciiMath: [$$("PreProcess",EXT.asciimath2jax)],)

- Rerun the test. The error is reported correctly: "TeX parse error (1): Undefined control sequence \c".

Thanks,
Fred

**Comment by pkra** [comment]
Thanks for the report. I'm unable to reproduce the issue. Could you post a full HTML markup that exhibits the problem?

Also, please note #206 -- we're planning to deprecate mj-page.

**Comment by pkra** [comment]
Also, could you add some information on your setup? mathjax-node version, node/npm versions etc.

**Comment by fptoth** [comment]
Hi,

The html file used to produce the error is the same as the equation above. See attached. No HTML markup other than the TeX itself.

We're using node version 4.4.0, npm version 2.14.20.

The version of mathjax-node is whatever we get when we run "npm install mathjax-node". I assume it's 0.5.1, but I'm not sure how to verify. Can you tell me how to confirm? I did a fresh install just yesterday.

[backslashc.zip](https://github.com/mathjax/MathJax-node/files/241165/backslashc.zip)

Thanks,
Fred

**Comment by fptoth** [comment]
Here's a transcript of me reproducing this error just now with a completely fresh install.

Thanks,
Fred

[wluser@icpa01 node_modules]$ ls
[EMPTY FOLDER]
[wluser@icpa01 node_modules]$ npm install mathjax-node
mathjax-node@0.5.1 mathjax-node
├── yargs@3.32.0 (decamelize@1.2.0, y18n@3.2.1, camelcase@2.1.1, window-size@0.1.4, cliui@3.2.0, string-width@1.0.1, os-locale@1.4.0)
├── speech-rule-engine@0.9.1 (xpath@0.0.23, xmldom@0.1.22, commander@2.9.0, xml-mapping@1.7.1)
├── jsdom@7.2.2 (acorn-globals@1.0.9, webidl-conversions@2.0.1, sax@1.2.1, abab@1.0.3, xml-name-validator@2.0.1, symbol-tree@3.1.4, tough-cookie@2.2.2, nwmatcher@1.3.7, cssom@0.3.1, parse5@1.5.1, acorn@2.7.0, whatwg-url-compat@0.6.5, escodegen@1.8.0, cssstyle@0.2.34, request@2.72.0)
└── mathjax@2.6.1

[wluser@icpa01 mathjax-node]$ cp ~/backslashc.html .

[wluser@icpa01 node_modules]$ ls
backslashc.html  mathjax-node/

[wluser@icpa01 node_modules]$ node -v
v4.4.0

[wluser@icpa01 node_modules]$ node ./mathjax-node/bin/page2mml < backslashc.html 
<!DOCTYPE html>
<html><head></head><body>$$VBeBorn=reflexiveVP\ (P.dirV2(v\_besch106{\hbox{<math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle displaystyle="true"><mo></mo></mstyle></math>}}na\c{s}te{\hbox{"}})).$$
</body></html>
[NOTE NO ERROR ABOVE]

[wluser@icpa01 node_modules]$ vi mathjax-node/lib/mj-page.js 
[EDIT as described in ticket, comment out line 652]  
                  
[wluser@icpa01 node_modules]$ node ./mathjax-node/bin/page2mml < backslashc.html 
TeX parse error (1): Undefined control sequence \c
<!DOCTYPE html>
<html><head></head><body><math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><merror><mtext>Undefined control sequence \c</mtext></merror></math>
</body></html>
[NOTE ERROR ABOVE]
[wluser@icpa01 node_modules]$>

**Comment by pkra** [comment]
Thanks for the additional information, Fred. 

The reason I could not reproduce this is that the TeX sample was modifed by markdown.

I see a problem but get the following result from your file:

```html
<!DOCTYPE html>
<html><head></head><body>$$VBeBorn=reflexiveVP\ (P.dirV2(v\_besch106{\hbox{<math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle displaystyle="true"><mo></mo></mstyle></math>}}na\c{s}te{\hbox{"}})).$$
</body></html>
```

I'm guessing this is just a precedence issue of the pre-processors -- te asciimath one runing before TeX one. Since page2mml is setup to use the default asciimath delimiters \`, it sees an empty equation, converts that to MathML, which then means the TeX pre-processor will ignore the equation (since it skips at most html tags).

You can simply use `page2mml --format "TeX"  < file.html` to limit which input processors are used. 

This would give you:

```html
TeX parse error (1): Undefined control sequence \c
<!DOCTYPE html>
<html><head></head><body><math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><merror><mtext>Undefined control sequence \c</mtext></merror></math>
</body></html>
```
