### ISSUE TITLE
extraneous delimiters cause unexpected results

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#226]
While responding to [@fptoth's comment](https://github.com/mathjax/MathJax-node/issues/206#issuecomment-216064704), I noticed that 

```latex 
$$  VBeBorn=reflexiveVP\ (P.dirV2(v\_besch106{\hbox{}}na\c{s}te{\hbox{"}})).$$
```

passed to `mj-single` would yield an empty result (e.g., `<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" />` etc.)

I'm not sure why the incorrect delimiters would throw mathjax-node off.

**Comment by pkra** [comment]
Oh, I see.

* https://github.com/mathjax/MathJax-node/blob/master/lib/mj-single.js#L105 sets delimiters `$$`
* https://github.com/mathjax/MathJax-node/blob/master/lib/mj-single.js#L669 wraps the input in the delimiters.

Was there a reason not to create the script directly tag?

**Comment by dpvc** [comment]
Do you mean that the dollar signs were passed as part of the math?  That would mean that the page would contain

    $$$$ ... $$$$

and so the first two dollars are matched be the second two, with no contents between them.  So the math expression is empty, and you would get an empty math output.  I assume you figured that out ("Oh, I see."), but I'm adding it here for documentation for the future.

You are right, adding a script of the proper type would probably be a better idea.

**Comment by dpvc** [comment]
The `issue226` branch includes the needed changes.  It also removes the need for the preprocessors, so I've removed them as well.

**Comment by pkra** [comment]
> Do you mean that the dollar signs were passed as part of the math?

Yes, that's what I had meant. Thanks for the quick fix!
