### ISSUE TITLE
[mj-single] [CHTML] reset internal ids

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#231]
Split out of https://github.com/mathjax/MathJax-node/issues/215#issue-148969074:

> CHTML id's may want to be reset every typeset so that (if used as the backend of some other service) the id's don't grow unbounded.
> ...
> So something like `MathJax.OutputJax.CommonHTML.ID = 0;` should do (untested).

**Comment by pkra** [comment]
I've confirmed that the fix works.

I'm not sure how to test this given that we drop them in #215.

**Comment by dpvc** [comment]
I don't think you can test for it.  I'd mark "No Test Needed" if we had that label.

**Comment by pkra** [comment]
Copy that.

**Comment by dpvc** [comment]
==> Merged.
