### ISSUE TITLE
Is MathJax-node not supportLaTex {matrix} Tag?

### ISSUE THREAD

**Issue by shanvenleo** [mathjax/MathJax-node#240]
I have a Tex '\left\{\begin{matrix}4x-3＞x\\x+4＜2x-1\end{matrix}\right.'
call 'mj-single.js' in MathJax-Node
```
// a simple TeX-input example
var mjAPI = require("mathjax-node/lib/mj-single.js");
mjAPI.config({
  MathJax: {
    // traditional MathJax configuration
  }
});
mjAPI.start();

var yourMath = '\left\{\begin{matrix}4x-3＞x\\x+4＜2x-1\end{matrix}\right.';

mjAPI.typeset({
  math: yourMath,
  format: "TeX", // "inline-TeX", "MathML"
  mml:true, //  svg:true,
}, function (data) {
  if (!data.errors) {console.log(data.mml)}
});
```

**> return Error
> TeX parse error: Undefined control sequence \x**

But when I use Mathjax.js in WebPage,the math appear normal. 

Is MathJax-node not support LaTex {matrix} Tag?

**Comment by pkra** [comment]
The errors stems from your linebreak `...\\x+4...` becoming `\x+4`. You need to escape backslashes in JavaScript strings.

**Comment by pkra** [comment]
FWIW, `var input = '\\left\\{\\begin{matrix}4x-3＞x\\\\ x+4＜2x-1\\end{matrix}\\right.';` will work as expected.

**Comment by shanvenleo** [comment]
thank you very much.
