### ISSUE TITLE
Pass a TeX string and return the rendered string

### ISSUE THREAD

**Issue by Menci** [mathjax/MathJax-node#251]
Now I can only pass a TeX string and a callback, when the TeX is finished rendering, the callback will be called with the rendered string.

Is there or will there be a function that I can call it and return the rendered string until it finished rendering(like KaTeX)?

**Comment by pkra** [comment]
MathJax (and thus MathJax-node) does not have a synchronous method. We are currently considering changes that might allow that in v3.0 but that is still in its planning phase.

**Comment by pkra** [comment]
BTW, if you're mostly trying to avoid callback hell in mathjax-node specifically, then you could wrap it in a promise, e.g.,

```javascript
var mjAPI = require('./lib/mj-single');
var mjPromise = function(options) {
  return new Promise(function(resolve, reject) {
    mjAPI.typeset(options, function(data) {
      if (data.errors){
        reject(data)
      }
      else {
        resolve(data)
      }
    });
  });
}

// usage:
mjPromise(options).then(
  (data) => console.log(data.html),
  (data) => console.log('There was a problem with the request: ' + data.errors)
 );
```
