### ISSUE TITLE
Example in README.md slightly broken

### ISSUE THREAD

**Issue by PatrickMassot** [mathjax/MathJax-node#253]
The example at the end of ``README.md``, covering the use of ``./lib/mj-page.js``, is slightly broken. It misses some escaping before ``\mathbb``. Adding ``<meta charset="UTF-8">`` would also help to immediately get the correct result as far as I can see.

**Comment by pkra** [comment]
Thanks for catching that. The readme has changed significantly on the develop branch, so this doesn't quite apply anymore (see also https://github.com/mathjax/MathJax-node/issues/206).

**Comment by PatrickMassot** [comment]
Thank you for your answer. I'm sorry I didn't think of looking at the develop branch (I'm not used to this big project workflow). About #206, see also my comment on #208: I'm a user of ``page2svg`` so I vote for keeping this functionality somewhere.
