### ISSUE TITLE
Suppress ids?

### ISSUE THREAD

**Issue by mattyod** [mathjax/MathJax-node#257]
Hi,

I'm using mathjax-node to generate some test fixtures and subsequently run tests against them. Due to the asynchronous way in which the fixtures are generated and the synchronous manner in which the tests are run I'm getting some conflicts in IDs such as: MJXc-Node-XX

I'm struggling a bit to find a way in which I can reset these for each fixture/test or just suppress them entirely. Does such a feature exist?

**Comment by pkra** [comment]
Thanks. This is a duplicate of #215 (which is fixed in `develop`).

**Comment by mattyod** [comment]
Cool thanks. This was a little while ago now will it release any time soon?
