### ISSUE TITLE
greek symbols not being rendered using page2html

### ISSUE THREAD

**Issue by newtechfellas** [mathjax/MathJax-node#261]
Given below text in input.html,  page2html is not displaying greek symbols.
`page2htlm <input.html >output.html`.
On viewing the output.html with Firefox/Chrome, greek symbols are not being displayed.
`
Suppose \(\alpha,\beta,\gamma\) are roots of \(x^3+x^2+2x+3=0\). If f(x)=0 is cubic polynomial equation whose roots are \(\alpha+\beta,\beta+\gamma,\gamma+\alpha\) then f(x)=
`
Browser displayed content.
![screen shot 2016-09-22 at 10 19 33 pm](https://cloud.githubusercontent.com/assets/6200948/18773217/bd97c7ee-8112-11e6-90a4-61f4700525ff.png)

**Comment by pkra** [comment]
Please post the complete output HTML. It looks like the typical result of not declaring UTF-8 in an HTML file.

**Comment by newtechfellas** [comment]
that was it. thanks. adding utf-8 charset resolved it.

**Comment by pkra** [comment]
Thanks for the follow up. Good to hear you could fix it.
