### ISSUE TITLE
jsdom 7.x onward only works on Node.js 4 or newer

### ISSUE THREAD

**Issue by tobiasschweizer** [mathjax/MathJax-node#265]
I installed `mathjax-node` using `npm install mathjax-node`. 

When I wanted to start a script, I got the following error:

```
mathjaxnode/node_modules/mathjax-node/node_modules/jsdom/lib/jsdom.js:3
() => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
 ^

```

The problem was that my nodejs version was outdated (on Ubuntu): `v0.10.25`

I followed [these](http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version) instructions and now it works fine.

Probably you could add an information to the README that you require at least `nodejs`.

**Comment by pkra** [comment]
Thanks for raising this. 

(FWIW, v0.10.25 is very very old :frowning: and ubuntu's shortcoming well documented.)

**Comment by pkra** [comment]
Fixed in `develop`.
