### ISSUE TITLE
SetWH is not defined error

### ISSUE THREAD

**Issue by akuma** [mathjax/MathJax-node#268]
sample:

``` bash
page2png < a.html > b.html
```

error:

```
mathjax-node/lib/mj-page.js:834
    SetWH(img,w,h); // work around jsdom bug with width and height CSS
    ^

ReferenceError: SetWH is not defined
```

**Comment by pkra** [comment]
Please provide a minimal example HTML file that reproduces the issue.

**Comment by akuma** [comment]
I use this example:

```
The well known Pythagorean theorem \(x^2 + y^2 = z^2\) was
proved to be invalid for other exponents.
Meaning the next equation has no integer solutions:

\[ x^n + y^n = z^n \]
```

**Comment by dpvc** [comment]
The `SetWH()` function was removed in commit 5f9226c8 (after the jsdom library was patched to properly maintain the svg element's width and height, but apparently not all instances of `SetWH()` were removed.  There appear to be two left, and they should be removed.

**Comment by pkra** [comment]
Note also https://github.com/mathjax/MathJax-node/issues/206

**Comment by pkra** [comment]
This issue applies only to mj-page which will be moved out of mathjax-node in the next release (see #206). 

Not sure how to tag this issue but I think it can be closed. What do you think @dpvc @zorkow ?

**Comment by dpvc** [comment]
Since it is a breaking bug in the current version, it might be worth a hot fix to master even through it doesn't go into develop.

**Comment by pkra** [comment]
Ok with me. Could you make a branch that fixes this? We can tag a release from that branch which will get pushed to NPM (thus avoiding re-basing problems for develop).

**Comment by pkra** [comment]
@dpvc I've created a branch for this issue (which should **not** be merged I think). All [I did there](https://github.com/mathjax/MathJax-node/blob/issue268/lib/mj-page.js) was remove the two calls to `SetWH` -- is that all?

**Comment by dpvc** [comment]
Yes, I think that should do it (I haven't run the code to check, but the `cssText` in the objects created just before the removed calls should include the width and height values.  So removing the `SetWH()` calls should be all there is to it.

**Comment by pkra** [comment]
Well, it seems to fix the example above.

@akuma can you try this fix out using  `npm install mathjax/mathjax-node#issue268` (by downloading the `issue268` branch)?

**Comment by akuma** [comment]
OK, I will try it later.

**Comment by pkra** [comment]
As per F2F, this is ready for release.

**Comment by pkra** [comment]
A release off the issue branch has been created https://github.com/mathjax/MathJax-node/releases/tag/0.5.2

**Comment by pkra** [comment]
Oops. I screwed up the release. Give me a minut.

**Comment by pkra** [comment]
Alright. Release is fixed now.
