### ISSUE TITLE
output math as PNG image

### ISSUE THREAD

**Issue by episodeyang** [mathjax/MathJax-node#27]
Hi @dpvc , @pkra, 
  
Thanks for this great library! What's the configuration to convert svg to png images? I followed the instruction and now have the batik library uncompressed inside the `batik` folder. 

If I pass 
```
data = {
    renderer: 'png',
    html: '<p>some html ....</p>'
```

MathJax-node gives me an error message:
`file failed to load: file:///project_folder/node_modules/MathJax-node/mathjax/unpacked/jax/output/png/config.js`

Thanks!

**Comment by pkra** [comment]
This was resolved with https://github.com/mathjax/MathJax-node/commit/d581791176a27355aea35dbac911aa83175a7201 I think.
