### ISSUE TITLE
[SVG output] mspace with cm units behaving badly

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#275]
E.g., `E_iE_j=E_jE_i,\quad F_iF_j=F_jF_i,\quad \hspace{2.1cm} {\mathrm{if}}\ |i-j|>1` renders fine in the browser but in mathjax-node the content beyond the mspace is move to the beginning of the line, overlapping with the other content.

**Comment by dpvc** [comment]
I'm not able to reproduce.  What branch are you on, and what is the call you are making?

**Comment by dpvc** [comment]
OOPS, sorry, was using CHTML rather than SVG.  Now I see it.

**Comment by dpvc** [comment]
I made a pull request (#276) with the fix.

**Comment by pkra** [comment]
Awesome. Thanks, Davide!

**Comment by pkra** [comment]
=> fixed in develop.
