### ISSUE TITLE
npm "Refusing to install mathjax-node as a dependency of itself"

### ISSUE THREAD

**Issue by alecjacobson** [mathjax/MathJax-node#278]
On Mac OS X, I installed nam using home-brew

    brew install npm

Then I tried to install mathjax-node using

    npm install mathjax-node

But saw this error:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install" "mathjax-node"
npm ERR! node v7.1.0
npm ERR! nam  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install mathjax-node as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     .../npm-debug.log
```

I did manage to get mathjax-node installed by cloning this repo from git and then issuing:

    npm install

(without an argument) in the main directory of this repo.

**Comment by pkra** [comment]
Is the working folder or package.json `name` called `mathjax-node` by any chance? That would lead to such an error.

**Comment by alecjacobson** [comment]
Ah. Indeed, I was trying to call this from within my MathJax-node clone
(and I guess the capitalization of MathJax doesn't save me on Mac OS X).

Thanks, that was quite a gotcha.

**Comment by pkra** [comment]
Thanks for confirming. 

I'm afraid that's NPM's intended behavior and there's nothing we can do about it.
