### ISSUE TITLE
TeX parse error: Missing close brace

### ISSUE THREAD

**Issue by MissMyCat** [mathjax/MathJax-node#287]
commend:  node d:\node_modules\mathjax-node\bin\tex2svg E=n\frac{B{{a}^{2}}}{2\Delta t}
while run this comend , TeX parse error: Missing close brace.

I do not change anything in tex2svg file, just generate svg.
btw, when I use another tex, the result is wrong either
for example:
node d:\node_modules\mathjax-node\bin\tex2svg S=\frac{1}{2}{{a}^{2}}
result is  s = (1/2) * a * 2 rather than  s = (1/2) * a ^ 2
os:win 10
MathJax-node version:0.5.2

**Comment by dpvc** [comment]
Make sure you enclose the TeX code in quotation marks, to make sure special characters aren't interpreted by the shell.  For example, in your first example, the space between `Delta and t` is breaking the TeX into to parameters for tex2jax, and only the first one is processed.  It is missing the closing brace (which is part of the second argument), which is the source of the error message you are receiving.

So use

    node d:\node_modules\mathjax-node\bin\tex2svg 'E=n\frac{B{{a}^{2}}}{2\Delta t}'

instead.

**Comment by MissMyCat** [comment]
@dpvc thx
I have tried use 
`node d:\node_modules\mathjax-node\bin\tex2svg 'E=n\frac{B{{a}^{2}}}{2\Delta t}'`
but it does not work
luckly, use 
`node d:\node_modules\mathjax-node\bin\tex2svg "E=n\frac{B{{a}^{2}}}{2\Delta t}"`
is Ok

**Comment by MissMyCat** [comment]
@dpvc 
I'm sorry I have another question.
when there is space in math content. such as : 
`node D:/node_modules/mathjax-node/bin/tex2svg "-c\leqslant x\leqslant c" `
program will return error:
Usage: tex2svg [options] 'math' > file.svg
Options:
  --inline       process as in-line TeX                                [boolean]
  --speech       include speech text                                   [boolean]
  --speechrules  ruleset to use for speech text (chromevox or mathspeak)
                                                          [default: "mathspeak"]
  --speechstyle  style to use for speech text (default, brief, sbrief)
                                                            [default: "default"]
  --linebreaks   perform automatic line-breaking                       [boolean]
  --font         web font to use                                [default: "TeX"]
  --ex           ex-size in pixels                                  [default: 6]
  --width        width of container in ex                         [default: 100]
  --extensions   extra MathJax extensions e.g. 'Safe,TeX/noUndefined'
                                                                   [default: ""]

Not enough non-option arguments: got 0, need at least 1

So. How can I transfer it ?

**Comment by dpvc** [comment]
The reason you get this message is because the `-c` from `"-c\leqslant x\leqslant c"` looks like a command line option (anything starting with a `-` does), and the tex2svg program complains.

Instead, use 

    node D:/node_modules/mathjax-node/bin/tex2svg -- "-c\leqslant x\leqslant c"

where the `--` ends the the options allowing the `"-c\leqslant x\leqslant c"` to be treated as a non-option argument (the math).  This is standard unix practice as a means of separating options from other arguments when the first argument contains a minus.  Note that you can use `--` even if the first argument doesn't start with `-`.

**Comment by MissMyCat** [comment]
@dpvc cool! It works!
