### ISSUE TITLE
options for tweaking font fallback behavior

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#299]
From https://github.com/mathjax/MathJax-dev/issues/22#issuecomment-282081720

> MathJax-node can't measure the width of elements, like MathJax can in the browser. [...] So MathJax-node has to guess.  It does this by using the "monospace" font, and making an assumption about the width of that font.  For standard ASCII characters, this assumption is reasonable, but for non-western characters, this doesn't work so well. 

> You can adjust the width that MathJax-node uses by changing the `8.5` in [line 318](https://github.com/mathjax/MathJax-node/blob/master/lib/mj-single.js#L318) of `lib/mj-single.js` to be something larger; a value of 13 worked for me.  If you change the `monospace` to `serif` two lines later, then you might need to go to 15 or 16. 

I'm wondering: Should we expose this in the configuration options?

**Comment by dpvc** [comment]
Fine by me, if you want to take time to do it and maintain it.

**Comment by pkra** [comment]
This was fixed by #358.
