### ISSUE TITLE
Autoloading of color extension not working

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#31]
E.g.,

    $ node bin/tex2svg --inline '\definecolor{red}{RGB}{255,0,0}\color{red}e^{i \pi} + 1 = 0'

returns with

    TeX parse error: Undefined control sequence \definecolor

But 

    $ node bin/tex2svg --inline '\require{color}\definecolor{red}{RGB}{255,0,0}\color{red}e^{i \pi} + 1 = 0'

works fine.

**Comment by dpvc** [comment]
This should be resolved with v2.5 (via the MathJax issue above).

**Comment by pkra** [comment]
Fixed in 0.3
