### ISSUE TITLE
any way to reset equationNumbers?

### ISSUE THREAD

**Issue by beeplin** [mathjax/MathJax-node#321]
It seems that  if set `{equationNumbers: 'AMS'}`, as long as `mathjax-node` is required into NodeJS and the code begins to run, the equation number is always increasing, and there is no way to reset the equationNumber to 1.

But since people always use mathjax-node to render lots of files for one time, is it possible to have an API to manually reset the equation number to 1 when we finish rending one file and start another?

**Comment by pkra** [comment]
They are stored in `state` (`state.AMS.startNumber` to be precise), so you could reset that when you need to. Not sure there's a more direct path right now.

**Comment by dpvc** [comment]
If you are not passing a `state` object, the numbers *should* be reset automatically.  If you *are* using the state, then either do as Peter suggested to reset it by hand (though you might need to set it to 0 rather than 1), or replace the `state` with a new blank `{}`.

**Comment by beeplin** [comment]
got it. Now it works for `mathjax-node` but in `mathjax-node-page` the equation number still can't be reset before each `mjpage` call. I will open an issue in the mjpage repo.

**Comment by beeplin** [comment]
OK I got how to do it in `mathjax-node-page`. As long as we don't pass `state` into `mjpage`'s third parameter, `mjpage` will automatically handle the equation numbers.
