### ISSUE TITLE
add support for webpack

### ISSUE THREAD

**Issue by peteinba** [mathjax/MathJax-node#332]
Hello! This is a feature request for supporting webpack. at the moment there is an "Cannot find module '.'" in xmlhttprequest.js error.
![error](https://cloud.githubusercontent.com/assets/3646685/26520028/0c0482e4-42cb-11e7-8b32-4c5a9cf1e703.png)

**Comment by pkra** [comment]
Client-side use is not supported. Use MathJax for this.

Closing this in favor of https://github.com/mathjax/MathJax-node/issues/147
