### ISSUE TITLE
Documentation for using typset on regular expression matches?

### ISSUE THREAD

**Issue by johnstephens** [mathjax/MathJax-node#340]
My node script imports an XHTML document, and exports it in ebook formats. Some of my source documents contain MathML markup in addition to other XHTML content. I'm trying to use MathJax-node along with [mathjax-node-svg2png][1] to replace the MathML with images.

[1]: https://github.com/pkra/mathjax-node-svg2png

Here's some of my dumb code:

```
var einstein = `
<blockquote class='eqtn'>
  <p>We will now prove the Pythogorian theorem: <mml:math> <mrow> <msup><mi> a </mi><mn>2</mn></msup> <mo> + </mo> <msup><mi> b </mi><mn>2</mn></msup> <mo> = </mo> <msup><mi> c </mi><mn>2</mn></msup> </mrow> </mml:math></p>
</blockquote>
<blockquote>
  <p><mml:math><mrow><mi>e</mi><mo>=</mo><mi>m</mi><msup><mi>c</mi><mn>2</mn></msup></mrow></mml:math></p>
</blockquote>
  `;

const re = /(\<mml:math.*?\<\/mml:math\>)/g;

var equations = einstein.match(re);

equations.forEach(equation => {

  mjAPI.typeset({
    math: equation,
    format: 'MathML',
    png: true,
    scale: 2
  }, function(data) {

    if(!data.errors) {

      const imageTag = `<img alt="${data.speakText}" src="${data.png}" width="80%"/>`;

      console.log(einstein.replace(equation, imageTag)); // This logs the string twice, each time with a different single equation replaced with an image tag.

    }

  });

});
```

I understand why this logs the output twice, and without updating the content, but I'm not sure how to pull it all together to replace all the equations with images, given that it's asynchronous. Is there any documentation that might point me in the right direction? If I had a better understanding of this, I would happily create or contribute to documentation explaining it.

Cheers!

**Comment by pkra** [comment]
You could try

```javascript
equations.forEach((equation, index) => {

  mjAPI.typeset({
    math: equation,
    format: 'MathML',
    png: true,
    scale: 2
  }, function(data) {

    if(!data.errors) {

      const imageTag = `<img alt="${data.speakText}" src="${data.png}" width="80%"/>`;

      einstein = einstein.replace(equation, imageTag);
      if (index === equations.length -1)      console.log(einstein)
    }

  });

});
```

The main issue is that you need to update the text to get the full output (your code was only logging out the result of a single replace without storing it). And you probably want to wait until the final equation is run to log out the result.

You'll still run into trouble with repeating equations, so you probably want to convert the matches to a set to avoid duplicates.

And, of course, the usual warning: https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454

**Comment by dpvc** [comment]
Peter's approach works, but it has an important drawback:  it will queue up all the typeset calls (one for each math element in the document) before any of them are processed.  If the document you are processing has lots of math in it, that could be inefficient in terms of memory usage.  It is better to only queue one typeset call at a time and have the callback start the next typeset operation.

Here's one way to do it:

```
//
//  The HTML snippet to process
//
const einstein = `
<blockquote class='eqtn'>
  <p>We will now prove the Pythogorian theorem: <mml:math> <mrow> <msup><mi> a </mi><mn>2</mn></msup> <mo> + </mo> <msup><mi> b </mi><mn>2</mn></msup> <mo> = </mo> <msup><mi> c </mi><mn>2</mn></msup> </mrow> </mml:math></p>
</blockquote>
<blockquote>
  <p><mml:math><mrow><mi>e</mi><mo>=</mo><mi>m</mi><msup><mi>c</mi><mn>2</mn></msup></mrow></mml:math></p>
</blockquote>`;

//
//  Split the HTML into MathML blocks and everythign inbetween them.
//  (the elements will aternate: HTML, then MathML, then HTML, then MathML, etc.)
//
let parts = einstein.split(/(\<mml:math.*?\<\/mml:math\>)/g);

//
//  Process the <mml:math> tag at position i in the parts array,
//    and move on to the next one when it is coomplete.
//  After all the math is processed, print the modified HTML snippet.
//
function mathToPng(i) {
    if (parts[i]) {
        mjAPI.typeset({
            math: parts[i],
            format: 'MathML',
            png: true,
            scale: 2
        }, function(data) {
            if (!data.errors) {
                parts[i] = `<img alt="${data.speakText}" src="${data.png}" width="80%"/>`;
            }
            mathToPng(i+2);
        });
    } else {
        //
        //  All the equations are done, so do whatever you want with the result
        //
        console.log(parts.join(''));
    }
}

//
//  Process the snippets starting with the first one
//
mathToPng(1);
```

This has the advantage of not having to repeatedly scan and modify the string (which is less inefficient).

**Comment by johnstephens** [comment]
Thank you so much! It never dawned on me that you could us a regular expression to split a string—that came in handy for another node script I was working on too.
