### ISSUE TITLE
Request html output produce correct symbolic representation.

### ISSUE THREAD

**Issue by timmackey** [mathjax/MathJax-node#346]
Would like to see mathjax-node emit accurate HTML output with symbology similar to mathjax.org  live demo.
![mathjax-sum-expression](https://user-images.githubusercontent.com/16199122/28495960-5a91d56e-6f13-11e7-8841-142cf46d4acf.jpg)
## mathjax-node typeset({ math: '\sum_{n=1}^{\infty} 2^{-n} = 1', html:true, css:true }, ...);

![mathjax-node-sum-expression](https://user-images.githubusercontent.com/16199122/28495962-60e69b5c-6f13-11e7-8f66-16ea0962bbe5.jpg)
--------------------------------------------------------------------------------------------------------
![mathjax-quadratic-formula](https://user-images.githubusercontent.com/16199122/28495965-66010fd2-6f13-11e7-88e0-3b8d19a15a28.jpg)
## mathjax-node typeset({math: ''x = {-b \pm \sqrt{b^2-4ac} \over 2a}'', html:true, css:true}, ...);

![mathjax-node-quadratic-formula](https://user-images.githubusercontent.com/16199122/28495967-6bd9feaa-6f13-11e7-81cb-21de5a20f8d2.jpg)

**Comment by dpvc** [comment]
In Javascript strings, the backslash is used as an "escape character" to allow you to create non-printing character like newlines (`\n`) and tabs (`\t`), so if you want to include a literal backslash in your string (as you do for TeX code), then you must escape the backslash as `\\`.   So use

```
mathjax-node typeset({ math: '\\sum_{n=1}^{\\infty} 2^{-n} = 1', html:true, css:true }, ...);
```

for example.  This is standard practice for Javascript strings.

**Comment by timmackey** [comment]
Thank you clearing this up!
