### ISSUE TITLE
Reverse render process. Need text from SVG.

### ISSUE THREAD

**Issue by mitorski** [mathjax/MathJax-node#360]
So i have strange case... I have a lot of svg images... more than 10.000, and i need get expression from the it and save into databse.  Any idea?

**Comment by pkra** [comment]
I'm not sure how this fits on this tracker. Were the equations generated with mathjax-node? In any case, there are no built-in features unless the creators has embedded the original source. 

For general equation OCR, you'll want to post to a more general forum such as stackoverflow.
