### ISSUE TITLE
Accented i in TeX font

### ISSUE THREAD

**Issue by codificador-nocturno** [mathjax/MathJax-node#362]
Hi, thanks for your hard work in this library!

We are having a small issue with the accented **i** with TeX font. The **i** is rendered with the dot and also with the accent symbol so it looks very strange (I'm attaching an screenshot). It should be rendered with the accent symbol and without the dot like in **í**

Thank you!

![screen shot 2017-09-27 at 09 26 03](https://user-images.githubusercontent.com/17958346/30919273-80afa758-a366-11e7-945b-51c3f0e508da.png)

**Comment by pkra** [comment]
Can you please provide some example code?

**Comment by codificador-nocturno** [comment]
Of course, this should work:

```
var mjAPI = require("mathjax-node");
mjAPI.config({
    MathJax: {
	SVG: {
	    font: 'TeX'
	}
    }
});
mjAPI.start();

mjAPI.typeset({
	math: 'C=\{x | x\ es\ un\ pa\acute{i}s\}',
	format: 'TeX',
	svg: true
    }, function (data) {
	if (!data.errors) {
        //add data.svg to html page ...	   
	} 	
    });

```
All other accented vowels (á, é, ó, ú) look good, it's just the accented i ( í ) that looks strange.

Thank you!

**Comment by pkra** [comment]
This is expected behavior and matches real TeX layout.

You could use `\imath` instead of `i` to get what you're after but it would generally be better to wrap text in `\text{}` and use the appropriate Unicode `í` or html entity, e.g., `&iacute;`.

**Comment by codificador-nocturno** [comment]
It's solved thanks! just for the record math should be:

C=\{x | x\ es\ un\ pa\acute{\imath}s\}

in order to render:

![screen shot 2017-09-27 at 15 04 46](https://user-images.githubusercontent.com/17958346/30935191-896707b8-a395-11e7-92ac-aa8a39bfdec6.png)
