### ISSUE TITLE
css path in test files

### ISSUE THREAD

**Issue by mathsbeauty** [mathjax/MathJax-node#369]
The following css path is given in test files.
http://www.mathjax.org/wp-content/themes/mathjax/style.css

However this file no longer exist. As such test files don't work.  Where the css files can be downloaded?

**Comment by pkra** [comment]
Thanks for catching that. And wow, that's old...

@dpvc @zorkow any objections to removing these files?

**Comment by mathsbeauty** [comment]
The test files should work... So links to css files may be updated or offline css files may be provided

**Comment by pkra** [comment]
> The test files should work...

I don't think they do anymore. All but one of these files are HTML, requiring the deprecated `mj-page` part of mathjax-node.

**Comment by dpvc** [comment]
> @dpvc @zorkow any objections to removing these files?

None from me.

**Comment by pkra** [comment]
Fixed in develop
