### ISSUE TITLE
singleton module prevents simultaneous multiple configurations

### ISSUE THREAD

**Issue by anandthakker** [mathjax/MathJax-node#37]
The problem: there's important [module-scoped variables](https://github.com/mathjax/MathJax-node/blob/master/lib/mj-page.js#L62-L80) in mj-page, making it a singleton.  This makes it awkward to have multiple configurations going in the same program.  And actually, because of #36, there's no clear workaround.  Conversely, changing this would basically remove the need for restarting MathJax, which is what 36 is about.

Two use cases for why it would be good to have the API be "instanceable":
1. A prerender server that takes the output format as a query parameter.  (I'm working on one now, in fact.)
2. Testing: running the API (or something that depends on it) through multiple tests is currently problematic.

I'm advocating for something like:

``` javascript
var mathjaxnode = require('MathJax-node');

var api1 = mathjaxnode(config1);
var api2 = mathjaxnode(config2);
```

Where `config1` and `config2` are configuration objects in the form currently expected by `config()`.

Happy to work up a PR for this if the maintainers are in support.

**Comment by pkra** [comment]
This bug is about `mj-page` so please note #206; I'm guessing some of this applies to `mj-single` as well though.

**Comment by pkra** [comment]
I'm not sure what to do about this issue. It's an upstream issue and we plan to address it in MathJax v3. However, we expect MathJax v3 to run in nodejs straight away, so mathjax-node will become somewhat obsolete. Also, in my experience, the most commonly requested configuration changes (e.g., input and output options, pre-processor configurations) can be changed relatively easily, especially when re-building `mj-page` using `mj-single`/`main`.

I'm leaning towards closing this.

**Comment by anandthakker** [comment]
👍 I'm fine closing this, esp. given the note about MathJax v3.

**Comment by pkra** [comment]
@anandthakker I'd still be curious to learn more about the configuration options that were causing issues for you.

**Comment by anandthakker** [comment]
@pkra ack... unfortunately, the use case is long gone, and I don't actually remember the specific config options that were problematic.

**Comment by pkra** [comment]
Ah, I had feared as much. Thanks for the follow up!
