### ISSUE TITLE
Install gives deprecation warning on one dependency

### ISSUE THREAD

**Issue by dietmarw** [mathjax/MathJax-node#370]
Installing the latest version v1.2.1 gives the following warning
```
npm WARN deprecated content-type-parser@1.0.2:
  This package has been renamed whatwg-mimetype; please upgrade.
```
So it would be good to update the dependency.

**Comment by dpvc** [comment]
Mathjax-node has only two direct dependencies:  jsdom and MathJax itself.  So this dependency probably is coming from jsdom, and would need to be reported there, as it is not something we can change ourselves.

**Comment by dietmarw** [comment]
Ah ok. I was confused by the `package-lock.json` file. So this can probably closed then.

**Comment by dietmarw** [comment]
Now that I now what to look for I found an already existing ticket on this :-)  tmpvar/jsdom#2078

**Comment by dpvc** [comment]
Thanks for the report, and the follow up.  We appreciate it even if it wasn't something we could fix.

**Comment by pkra** [comment]
In summary, this is a duplicate of #325 as only upgrading jsdom past v10 will get us this fix.
