### ISSUE TITLE
SVG unknown char messages when SVG output is not set

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#378]
Originally reported at https://github.com/pkra/mathjax-node-page/issues/56.

The following will produce `"SVG - Unknown character: U+C in MathJax_Main,MathJax_Size1,MathJax_AMS"` etc.

```
var mjAPI = require("mathjax-node");
mjAPI.typeset({
  math: 'a = \frac{\text{some text with umlauts äöü}}{1.23}',
  format: "TeX", // "inline-TeX", "MathML"
  mml:true,
}, function (data) {
  if (!data.errors) {console.log(data.mml)}
});
```

On the other hand, there are no MML Unknown Char messages so I'm guessing the message hooks are not set up correctly. Maybe they should just be independent of the output anyway?

**Comment by dpvc** [comment]
I've made a pull request to fix the issue.

**Comment by dpvc** [comment]
==> Merged.
