### ISSUE TITLE
[readme] document v2.0.0 requirements

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#383]
The readme could mention that mathjax-node now requires node 6+ and jsdom 10+. 

The breaking changes from v1 (and v2) can probably move to the bottom. Related libraries probably as well.

**Comment by dpvc** [comment]
Yes, I saw that when I checked the 2.0 release on npmjs.  Was planning to do something about it today.  Thanks for checking.

**Comment by dpvc** [comment]
I've updated the README, and will tag it as a new release so that `npmjs` will grab the new README.

**Comment by pkra** [comment]
Thanks, Davide. All fixed.
