### ISSUE TITLE
Do mathjax-node support MathJax@3

### ISSUE THREAD

**Issue by hjy1210** [mathjax/MathJax-node#466]
After install mathjax-node@2.1.1, I found it dependents on mathjax@2.7.9.

So, I wonder do mathjax-node support MathJax@3

**Comment by pkra** [comment]
You can use mathjax v3 directly, see https://github.com/mathjax/MathJax-demos-node for some examples.

**Comment by dpvc** [comment]
As Peter says, mathjax-node is not needed for MathJax version 3, since you can call v3 directly from node.  Mathjax-node was needed for v2 since version 2 was not designed to work as a node module.
