### ISSUE TITLE
Cannot get the same result with mathjax-node as with MathJax on the browser

### ISSUE THREAD

**Issue by RonaldBecerra** [mathjax/MathJax-node#475]
I want to render some formulas with mathjax-node, but also the user should be able to individually select each of the elements underlining them with the cursor. For example, if a summation appears, he could select the extreme values, the elements of the internal formula, the iteration variable, and so on. Apparently, this is only possible when the formula is rendered as \<span> objects, which is achieved with the html property:

var mjAPI = require("mathjax-node");
mjAPI.config({
    MathJax: {
        // traditional MathJax configuration
    }
});
mjAPI.start();

var yourMath = '\sum_{i=0}^ni>2';

let result = mjAPI.typeset({
    math: yourMath,
    format: "inline-TeX", 
    html: true
},

But the problem is that it then prints something like this:

![image](https://user-images.githubusercontent.com/25404892/141944587-13ae9e60-e1f8-4f88-94c4-564255fc6f88.png)

and it can be seen that the summation is not correctly rendered. When I was using MathJax 2.7 directly on the browser, I could get:

![image](https://user-images.githubusercontent.com/25404892/141945102-9a1d32a8-b8a8-4156-8b0c-15ae19b0d2be.png)

**Comment by pkra** [comment]
The second screenshot indicates you want display mode but your configuration sets `format: "inline-TeX"`. Try `format: "TeX"` instead (and check the readme for more information).

(Also: consider switching to MathJax v3 which works in nodejs directly, see https://github.com/mathjax/MathJax-demos-node for some examples.)

**Comment by RonaldBecerra** [comment]
@pkra The problem with MathJax v3 is that it does not allow the user to select (underline) portions of the rendered formula or even it as a whole, a feature that I need. I have only achieved that when the returned HTML code consists on \<span> objects, that v2 gives.

(I haven't put the backlash (\) in my original comment, so the \<span> was not shown. Sorry for that).

With "mathjax-node" the returned code consists on \<span> objects when I put `html:true` in the typeset, and then use `result.html`, but it does not render as desired. I already tried with `format:"TeX"`, but I got:

![image](https://user-images.githubusercontent.com/25404892/142028793-5a4a8bc4-4980-4567-8ab2-89c4efa7b3ec.png)

**Comment by pkra** [comment]
That image looks like the CSS is missing completely. Try posting a full self-contained output example somewhere people can access.

**Comment by RonaldBecerra** [comment]
@pkra Ok, I am working with two files. The first one is called "index.html". The user inputs a formula in there and sends it to a server. The code is:

`<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<title>MathJax example V3</title>
		<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
	</head>

	<body>
		<form action="http://localhost:90/example" method="POST">
			Formula: <input type="text" name="latexFormula"><br>
			<button type="submit">Send to backend</button>
		</form>
		<p>Click on the submit button, and the input will be sent to a page on the server.</p>
	</body>
</html>`

The second one is called App.js, which has the server that runs "mathjax-node" and returns the HTML code on a different page:

`// ----------------- Express server -----------------
const express = require('express');
const bodyParser = require('body-parser');
const app = express();

app.use(bodyParser.urlencoded({ extended: true })); 

app.post('/example', async(req, res) => {
    let result = await returnMathJax(req.body.latexFormula);
    res.send(result.html);
});

const port = 90;

app.listen(port, () => {
    console.log(`Server running on port ${port}`);
});

// --------------- MathJax configuration -----------
var mjAPI = require("mathjax-node");
mjAPI.config({
    MathJax: {
        jax: ["input/TeX","output/HTML-CSS"],
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true,
        },
        TeX: {extensions: ["AMSmath.js","AMSsymbols.js"]},

        "HTML-CSS": {
            linebreaks: { automatic: true },
            fonts: ["TeX"],
        }
    },
});
mjAPI.start();

// ---------------- Execute MathJax -----------------
async function returnMathJax(formula){  
    let result = await mjAPI.typeset({
        "format":"TeX", 
        "math": formula,
        "html": true, 
        "htmlNode": true,
        "css": true,
    });
    return result;
}`

**Comment by RonaldBecerra** [comment]
@pkra Ok, I am working with two files. The first one is called "index.html". The user inputs a formula in there and sends it to a server. The code is:

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<title>MathJax example V3</title>
		<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
	</head>

	<body>
		<form action="http://localhost:90/example" method="POST">
			Formula: <input type="text" name="latexFormula"><br>
			<button type="submit">Send to backend</button>
		</form>
		<p>Click on the submit button, and the input will be sent to a page on the server.</p>
	</body>
</html>
```
The second one is called App.js, which has the server that runs "mathjax-node" and returns the HTML code on a different page:

```
// ----------------- Express server -----------------
const express = require('express');
const bodyParser = require('body-parser');
const app = express();

app.use(bodyParser.urlencoded({ extended: true })); 

app.post('/example', async(req, res) => {
    let result = await returnMathJax(req.body.latexFormula);
    res.send(result.html);
});

const port = 90;

app.listen(port, () => {
    console.log(`Server running on port ${port}`);
});

// --------------- MathJax configuration -----------
var mjAPI = require("mathjax-node");
mjAPI.config({
    MathJax: {
        jax: ["input/TeX","output/HTML-CSS"],
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true,
        },
        TeX: {extensions: ["AMSmath.js","AMSsymbols.js"]},

        "HTML-CSS": {
            linebreaks: { automatic: true },
            fonts: ["TeX"],
        }
    },
});
mjAPI.start();

// ---------------- Execute MathJax -----------------
async function returnMathJax(formula){  
    let result = await mjAPI.typeset({
        "format":"TeX", 
        "math": formula,
        "html": true, 
        "htmlNode": true,
        "css": true,
    });
    return result;
}
```

**Comment by pkra** [comment]
You never do anything with `result.css` so the necessary CSS is missing.

Since `result.css` is actually fixed for each mathjax version, you could just call it once during development and store its output in a regular stylesheet to load into the page.

**Comment by RonaldBecerra** [comment]
@pkra Thank you, it worked. I had to use the `result.css` in the style of the web page. In the code above, I changed the server part:

```
app.post('/example', async(req, res) => {
    let result = await returnMathJax(req.body.latexFormula);
    let head = "<head><style>" + result.css.toString() + "</style></head>";
    let body = "<body>" + result.html.toString() + "</body>";
    let mypage = "<html>"+ head + body + "</html>";
    res.send(mypage);
});
```
And as you said, I could avoid calculating `result.css` everytime and just use its predetermined result.

**Comment by pkra** [comment]
Glad to hear you could work it out. (FYI This might be interesting: https://github.com/mathjax/MathJax-src/pull/734)
