### ISSUE TITLE
Undefined control sequence even after defining it

### ISSUE THREAD

**Issue by brunobmello25** [mathjax/MathJax-node#476]
I am trying to convert this content from LaTeX to MathML:

`
"\lambda \in \R"
`

By default the \R symbol should not be defined. I am defining it on the mathJax tex macros object, like this:

```
const converted = await mathjaxNode.typeset({
  math: "\lambda \in \R",
  format: 'TeX',
  mml: true,
  MathJax: {
    tex: {
      macros: {
        R: 'Reals',
      },
    },
  },
});
```

But still I get the following error:

`
TeX parse error: Undefined control sequence \R
`

I am using mathjax-node version 2.1.1

**Comment by dpvc** [comment]
You are providing a v3 configuration, but mathjax-node uses MathJax v2, so you would need to use

``` javascript
const converted = await mathjaxNode.typeset({
  math: "\lambda \in \R",
  format: 'TeX',
  mml: true,
  MathJax: {
    TeX: {
      Macros: {
        R: 'Reals',
      }
    }
  }
});
```

but I'm wondering if you have the correct definition for `\R`, as this will produce "λ ∈ *Reals*".  You might want to use

``` javascript
        R: '\\mathbf{R}',
```

 or

``` javascript
        R: '\\mathbb{R}',
```

instead.

Note that MathJax v3 can be used in node directly, so you might also consider switching from mathjax-node to MathJax v3.  See the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) repository for examples.  There are several different ways you can call MathJax v3 from node applications, and there are examples for each; seethe various subdirectories in that repository.

**Comment by brunobmello25** [comment]
Oh so that's what was happening! Thanks a lot! That solved the problem

I'll close this issue for now, and I'll also consider switching from mathjax-node to mathjax v3. Thanks again for the help!
