### ISSUE TITLE
Allow change of svg-to-PNG converter [was: Why not use "svg2png" , pure node without JAVA depend]

### ISSUE THREAD

**Issue by everyx** [mathjax/MathJax-node#59]
I hava some trouble in my vps about java environment configuration, and i find the node package "svg2png" and modify some code, i'll  submit a pull request about this for a review.

sorry for my poor english.

**Comment by pkra** [comment]
See also https://github.com/mathjax/MathJax-node/issues/65#issuecomment-73074306

**Comment by SamyPesse** [comment]
:+1:  [svgexport](https://www.npmjs.com/package/svgexport) works great

**Comment by pkra** [comment]
@SamyPesse see [my earlier comment](https://github.com/mathjax/MathJax-node/issues/59#issuecomment-66744347) regarding our original requirements.

**Comment by physikerwelt** [comment]
I agree that both solutions java and phantomjs are not ideal.
I think one of svgexports advantages is that no file needs to be written on "disk".
A node only solution would be awesome, but I guess it's a very challanging tasks, which can not be done a few after work sessions.
(ping @gwicke)

**Comment by pkra** [comment]
Some recent observations

* Over on the Wikimedia fork, there's a PR building on rsvg, https://github.com/wikimedia/MathJax-node/pull/16. Biggest immediate question from my end was: is that a bad dependency?
* But I just noticed that [jsdom now handles canvas](https://github.com/tmpvar/jsdom#canvas) via https://www.npmjs.com/package/canvas. That seem to me to be the most natural approach ("universal JS" etc) despite having similarly bad installation requirements on node.

**Comment by pkra** [comment]
Note: I haven't actually tested if the canvas solution for jsdom would be sufficient.

**Comment by gwicke** [comment]
Some quick notes from my end:

- We use (a patched version of) rsvg for SVG thumbnailing in production. It is working okay, but lacks support for some features like HTML-in-SVG. There is some RSVG-related discussion on https://phabricator.wikimedia.org/T40010.
- Latest phantomjs (2.0) is based on relatively recent Blink, so likely has similar SVG support as current Chrome. However, binding support for node is mostly still using phantomjs 1.9. We don't currently use phantomjs in production, but might reconsider it for tasks like HTML-to-PDF in the future.
- I can't vouch for the quality or performance of the jsdom canvas solution. The dependencies are manageable (we have a few services using it).

**Comment by d00rman** [comment]
My 2 cents here would be to develop an extension point for MathJax so that people can hook up and test whatever suits them better, while still having a sane default. What is that sane default is arguable, ofc, but the way I see it is that it's sane if it doesn't introduce many (especially binary) external dependencies regardless of the performance penalties or feature set. These could be then mitigated on a case-per-case basis with specialised converters.

**Comment by pkra** [comment]
Thanks for the feedbac, @gwicke @d00rman -- much appreciated!

**Comment by pkra** [comment]
See https://github.com/mathjax/MathJax-node/pull/174 for a first attempt.

**Comment by pkra** [comment]
Closed in favor of #205.
