### ISSUE TITLE
MathJax 2.5 related thread

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#64]
Once MathJax v2.5 is finalized, we should 

* [x] update the mathjax-node branch of MathJax core
* [x] increment MathJax-node version
* [x] publish MathJax-node to npm

**Comment by dpvc** [comment]
Do we want to got to the git-flow approach in this repository, too (by which I mean a `develop` branch with pulls to `master` representing releases, etc.)?

**Comment by pkra** [comment]
Yes, sounds good.

**Comment by dpvc** [comment]
OK, I'll set up the branches, and rebase my recent fixes.

**Comment by thomasfoster96** [comment]
Just wondering, how far away is MathJax-node from being published to npm? Installing packages via a Github URL is a bit touch and go on some setups, so going via npm would be a great help.

**Comment by pkra** [comment]
Pretty close https://github.com/mathjax/MathJax-node/pull/71

**Comment by pkra** [comment]
Finished.
