### ISSUE TITLE
Generate HTML/CSS output?

### ISSUE THREAD

**Issue by davidmerfield** [mathjax/MathJax-node#67]
My goal is to pass a Tex string to MathJax and receive HTML & CSS back. 

It looks like this library only allows you to output the math as SVG, PNG or MML. Do you intend to add HTML?

**Comment by pkra** [comment]
> Do you intend to add HTML?

We don't. But really, we can't --- the HTML-CSS output is very client dependent and cannot be re-used across browsers and platforms.

The new CommonHTML output (part of the just released MathJax 2.5) is desiged to be stable. However, it's not yet on par with HTML-CSS and SVG (in both features and layout quality).

**Comment by davidmerfield** [comment]
@pkra Thank you for your prompt response, this makes more sense to me now. 

I'll make do with KaTex in the meantime.
