### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by tobysharp** [mathjax/MathJax-node#76]
Hi. I'm trying to get started with MathJax-node and be able to run some simple examples. I want to be able to author files with both SVG and math content, and use MathJax-node to turn them into pure SVG.

I'm running on Windows.

After installing node.js, npm and python 2.7, I was able to run the npm install which completes with just a couple of warnings. Seeing that there were recently some issues resolved with running on Windows, I used git to checkout the 'develop' branch.

However, I'm new to this whole environment and could use a few hints. How do I convert math to SVG? Should I be able to run something like
  node tex2svg test-files/sample-tex.html > test.svg

Please could you post at least one command that I should be able to run if set up correctly to generate an output file. This will help me figure out whether I am getting the installation steps right. Thanks.

**Comment by pkra** [comment]
There are no examples in `/bin` that do provide this out of the box. Theoretically, page2svg could help but I don't know how well jsdom would handle an SVG (they are not focused on XML support). 

Also, it's not straight forward to have MathJax work inside an SVG (cf. http://stackoverflow.com/questions/15962325/mathjax-inside-svg). You could follow the idea from the second answer there: write your own wrapper that loops through the TeX fragments, runs tex2svg, and inserts the results into the larger SVG.

(FYI, check out https://github.com/mathjax/MathJax-node/issues/70 for Windows related issues.)

**Comment by tobysharp** [comment]
Thanks, but if MathJax-node doesn't do this, what does it do? Could you provide a couple of examples, with command lines using the sample files?

Sent from my Windows Phone
________________________________

**Comment by pkra** [comment]
> if MathJax-node doesn't do this, what does it do?

MathJax-node provides APIs to call MathJax from node.js programs. This repository also contains example programs (in `/bin`) of using those APIs.

> Could you provide a couple of examples, with command lines using the sample files?

Try runnning an example from `bin` or just read them.

* from `tex2svg`: "Usage: tex2svg [options] 'math' > file.svg"
* from `page2svg`: "Usage: page2svg [options] < input.html > output.html"

In other words, `tex2svg` converts a TeX string into an SVG, `page2svg` processes an HTML document, replacing mathematics with svg renderings. See each example for the specific options.

Perhaps you can explain what you're after in more detail. Also, IIUC the develop branch is not yet working on Windows as two PRs are not yet incorporated.

**Comment by tobysharp** [comment]
Thank you. I'm sure I will understand a little better when I have one or two of these simple examples running and can see how they work. Hopefully the fixes for Windows will be incorporated soon too. However I would suggest updating the readme file with at least one complete "getting started" example that can be run after installation to generate some sort of trivial output. IIUC this should work?:
node tex2svg 'x^2+y^2=r^2' > circle.svg

Thanks again.

Sent from my Windows Phone
________________________________

**Comment by dpvc** [comment]
Yes, your example should work.  And the develop branch should work in Windows except for PNG generation.
