### ISSUE TITLE
png conversion fails with mathjax 2.5.1

### ISSUE THREAD

**Issue by physikerwelt** [mathjax/MathJax-node#82]
see
https://gist.github.com/physikerwelt/48e477d2d5c093e5ecca

**Comment by physikerwelt** [comment]
caused by https://github.com/wikimedia/MathJax-node/commit/0e8143e6d11c67ed9c407c33593e45d0cd6045a6
If I revert the change I don't have problems

**Comment by pkra** [comment]
If you have the time, could you manually add a copy of the MathEvents extension to the MathJax copy in node_modules? See #85.

**Comment by dpvc** [comment]
This should be resolved by commit 0b4b10f listed above.
