### ISSUE TITLE
Move automated tests from Mathoid

### ISSUE THREAD

**Issue by physikerwelt** [mathjax/MathJax-node#83]
@pkra are you interested in getting automated unit tests from mathoid?
Most of them are related to MathJax-node anyhow.
I think it would be nice to see automatically if something fails.

**Comment by pkra** [comment]
Definitely interested. What kind of tests (framework, runner etc) are those?

**Comment by physikerwelt** [comment]
Let me create a pull request tomorrow... that will simplify the discussion

**Comment by pkra** [comment]
Thanks!

**Comment by physikerwelt** [comment]
oups... it took more than one day

**Comment by physikerwelt** [comment]
Here you can see the test coverage
https://coveralls.io/builds/2752607/source?filename=lib%2Fmj-single.js

**Comment by pkra** [comment]
Resolved by #114.
