### ISSUE TITLE
missing MathEvents extension

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#85]
It looks like #82 and the re-opened #66 are due to the MathEvents extension having been stripped from the slimmed-down copy of core MathJax.

@dpvc should I just add it back to the upstream mathjax-node branch or is this worth investigating?

**Comment by dpvc** [comment]
`MathEvents.js` is called in by all the output jax as they need it to attach the event handlers for things like the context menu and zoom clicking to the math output.  These handlers are in the `MathEvents.js` file.  Without it, you not only get the errors that you are seeing, but also have a 15 second delay as MathJax waits for the unavailable file to load.

I can add some code to `mj-page` and `mj-single` to compensate.

**Comment by dpvc** [comment]
I have pushed a change that should resolve the problem.

**Comment by pkra** [comment]
This hasn't been merged into develop?
