### ISSUE TITLE
Text generation omitting or incorrectly transcribing some symbols

### ISSUE THREAD

**Issue by sueannma** [mathjax/MathJax-node#87]
An user was trying to transcribe the below MathML and noted: "The description is leaving out the equal sign after Class Width and treating the approximately equal sign before 8.33 as a normal equal sign.": 

See inputted code and output results on MathML Cloud page at: 
https://mathmlcloud.org/#/equation/5519ae766432bdcab3a7b57a

**Comment by dpvc** [comment]
The MathML seems to be

    <math display="block" xmlns="http://www.w3.org/1998/Math/MathML" alttext="Class Width StartFraction Largest Score minus Smallest Score Over Number of Classes EndFraction equals StartFraction 50 Over 6 EndFraction equals 8.33">
    <mrow>
      <mtext>Class Width</mtext>
      <mo>=</mo>
      <mfrac>
        <mrow>
          <mtext>Largest Score</mtext>
          <mo>−</mo>
          <mtext>Smallest Score</mtext>
        </mrow>
        <mrow>
          <mtext>Number of Classes</mtext>
        </mrow>
      </mfrac>
      <mo>=</mo>
      <mfrac>
        <mrow>
          <mn>50</mn>
        </mrow>
        <mn>6</mn>
      </mfrac>
      <mo>≈</mo>
      <mn>8.33</mn>
    </mrow>
    </math>

This displays properly for me in HTML-CSS, SVG, and NativeMML output from MathJax.  It also seems to appear correctly in the page you link to, which includes the MathJax output.  So I assume that I'm misunderstanding the problem.  Can you verify that the MathML above is the one that doesn't work for you?

**Comment by sueannma** [comment]
If you compare the description included in quotes (that's the auto-generated text) and compare it against the inputted MathML, you’ll notice the following errors/omissions: 

•	Description is leaving out the first equal sign after "Class Width"
•	Description incorrectly treats the approximately equal sign (≈) before 8.33 as a normal equal sign

**Comment by dpvc** [comment]
Sorry, I missed that it was about the speech annotation and thought it was about the rendering.  That is what I was missing.

**Comment by sueannma** [comment]
No problem! Thanks for the quick replies! =)

**Comment by zorkow** [comment]
I can reproduce the bug. I will look into it.

**Comment by dpvc** [comment]
I can as well.  Apparently, it is the initial `<mtext>` that is the issue.  If I change that to `<mi>`, the equalities are properly handled (but of course, the rendering of the text is not the desired one when `<mi>` is used).

**Comment by zorkow** [comment]
Yes, the mtext is the problem. But it should still get the multi-relation right.

**Comment by zorkow** [comment]
Fixed the bug and pushed a new version to github and npm.

**Comment by sueannma** [comment]
Wow - that was amazingly fast! Thank you!!

**Comment by zorkow** [comment]
One line fix. No problem.

Davide, I've also updated the sre fork in MathJax. Anything else I need to do, to update in MathJax-node?

**Comment by dpvc** [comment]
@zorkow, no, your new version will be used automatically for new checkout of MathJax-node, or if someone does `npm update`.  I have checked that this occurs, and that the example MathML now gets the correct speech text.  Thanks!

**Comment by sueannma** [comment]
Hi Davide and Volker,

Do we need to do anything specific on the MathML Cloud side to make sure the revised grammar rules are applied? We just pulled in the latest code from MathJax-node (addressing a separate rendering bug), but we’re not seeing the expected corrections to the auto-generated text.

Thanks!
Sue-Ann

**Comment by zorkow** [comment]
Hi Sue-Ann,

I can't reproduce the problem. After running npm update I get the expected
output.
What is the version number of the speech-rule-engine package in your
node_modules folder?

Volker

**Comment by sueannma** [comment]
we're using the 0.2.5 package

**Comment by dpvc** [comment]
@sueannma, it sounds like you might have been using `git` and GitHub to get your copy of MathJax-node?  If that is the case, you probably want to switch to `npm`, as that will manage the dependencies better.  That used to be harder to do, but now you can just do

    npm install MathJax-node

to get MathJax-node.  If you have done that, then

    npm update

should get the the latest versions of all the dependencies, including the speech-rule-engine.

**Comment by zorkow** [comment]
@sueannma

> we're using the 0.2.5 package

That's indeed the latest version that contains the fix. Question is, does
you MathJax-node pull in the right version (see Davide's email about using
via npm).

./bin/mml2mml --speech "...."

I get the correct speech output:

alttext="Class Width equals StartFraction Largest Score minus Smallest
Score Over Number of Classes EndFraction equals StartFraction 50 Over 6
EndFraction almost-equals 8.33"

**Comment by sueannma** [comment]
Thanks both. I'm going to have someone from our engineering team follow-up directly on this one.
