### ISSUE TITLE
hung process with mathspeak

### ISSUE THREAD

**Issue by tiarno** [mathjax/MathJax-node#88]
If you pass a string with double quotes and speech is selected, the process will hang:

    tex2svg --speech '"x"'

Seems to be the speech engine, tex2mml responds the same way.

**Comment by dpvc** [comment]
I get the same results that you do.  @zorkow, can you look into it?

**Comment by zorkow** [comment]
This should work now. I've published a new version. Please update.

For the record: npm module xpath hangs on certain malformed xpath
expression, rather than throwing an exception.

**Comment by dpvc** [comment]
I confirm that the update works for me.  Thanks for the quick fix!

**Comment by pkra** [comment]
Should we file an upstream bug?

**Comment by zorkow** [comment]
I've just done that.
https://github.com/goto100/xpath/issues/28

**Comment by tiarno** [comment]
thanks, I'm looking forward to updating my install--but where is the update? the latest commit i see here on github is from a couple of weeks ago.

**Comment by dpvc** [comment]
@tiarno, the update is in the speech engine module that is a dependency of MathJax-node, not in MathJax-node itself.  If you run `npm update` in the MathJax-node directory, it should grab the updated speech engine for you.

**Comment by tiarno** [comment]
got it, thanks!

**Comment by zorkow** [comment]
FYI, the actual speech rule engine is at:
https://github.com/zorkow/speech-rule-engine
