### ISSUE TITLE
svg fraction scale values missing in path elements

### ISSUE THREAD

**Issue by corinnaSchultz** [mathjax/MathJax-node#93]
I'm not sure if this is a mathjax issue in particular, or an issue specific to mathjax-node.

I have useFontCache and useGlobalCache set to false, so the svg code that I get back contains `<g>` elements with `<path>` child elements. If I go to jsfiddle, and use the mathjax CDN link with the default config file for generating svg images, I get back `<g>` elements with `<use>` child elements. 
[ http://jsfiddle.net/PGhkg/5/ ]

The problem I'm seeing is that when I process mathML containing `<mfrac>` tags, the resulting `<path>` elements lack the "scale()" transform, except for the first child node in each `<g>` node. If I process the same mathML in the jsfiddle, the resulting `<use>` elements all have the correct "scale()" transforms. The result is that I see fractions that are poorly formatted.

I have tried several different expressions involving fractions: log with a base, a square root, other numbers. In each case, the first child `<path>` element is properly scaled, but the others aren't.

Sample mathML:
    `<math xmlns="http://www.w3.org/2010/Math/MathML"><mfrac><mn>1</mn><mn>16</mn></mfrac></math>`

The resulting svg:

    <svg xmlns:xlink="http://www.w3.org/1999/xlink" style="vertical-align: -1.167ex; margin-left: 0ex; margin-right: 0ex; margin-bottom: 1px; margin-top: 1px;" width="2.5ex" height="3.333ex" viewBox="0 -943.6 1074.2 1402.7" role="math" aria-labelledby="MathJax-Element-3-Title MathJax-Element-3-Desc">
    <title id="MathJax-Element-3-Title">Equation</title><desc id="MathJax-Element-3-Desc">one-sixteenth</desc>
    <g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)" aria-hidden="true"><g transform="translate(120,0)"><rect stroke="none" width="834" height="60" x="0" y="220"></rect>
    <g transform="translate(238,451)">
    <path stroke-width="10" transform="scale(0.707)" d="M213 578L200 573Q186 568 160 563T102 556H83V602H102Q149 604 189 617T245 641T273 663Q275 666 285 666Q294 666 302 660V361L303 61Q310 54 315 52T339 48T401 46H427V0H416Q395 3 257 3Q121 3 100 0H88V46H114Q136 46 152 46T177 47T193 50T201 52T207 57T213 61V578Z">
    </path></g>

    [here's the denominator of the fraction. The first path is the 1, the second path is the 6. 
    Notice the lack of scale on the 6, this makes it render at the normal font size.]

    <g transform="translate(60,-423)">
    <path stroke-width="10" transform="scale(0.707)" d="M213 578L200 573Q186 568 160 563T102 556H83V602H102Q149 604 189 617T245 641T273 663Q275 666 285 666Q294 666 302 660V361L303 61Q310 54 315 52T339 48T401 46H427V0H416Q395 3 257 3Q121 3 100 0H88V46H114Q136 46 152 46T177 47T193 50T201 52T207 57T213 61V578Z"></path>
    <path stroke-width="10" transform="translate(357,0)" d="M42 313Q42 476 123 571T303 666Q372 666 402 630T432 550Q432 525 418 510T379 495Q356 495 341 509T326 548Q326 592 373 601Q351 623 311 626Q240 626 194 566Q147 500 147 364L148 360Q153 366 156 373Q197 433 263 433H267Q313 433 348 414Q372 400 396 374T435 317Q456 268 456 210V192Q456 169 451 149Q440 90 387 34T253 -22Q225 -22 199 -14T143 16T92 75T56 172T42 313ZM257 397Q227 397 205 380T171 335T154 278T148 216Q148 133 160 97T198 39Q222 21 251 21Q302 21 329 59Q342 77 347 104T352 209Q352 289 347 316T329 361Q302 397 257 397Z">
    </path></g></g></g></svg>

**Comment by dpvc** [comment]
It turns out that this is an issue with MathJax itself.  In the case where the paths are included directly (`useFontCache` is false), the scaling is set, but when the positioning is done, the `transform` is replaced by a `translate()` and the `scale()` is lost.  I have the fix prepared, but it will be in the MathJax repository, and won't appear until v2.6 or later.

Unfortunately, I don't have a temporary patch for you.  The only suggestion I have is to set `useFontCache` to `true` and `useGlobalCache` to `false`, so each equation will have all the paths within its main SVG element, but with a local cache rather than a shared cache.

**Comment by corinnaSchultz** [comment]
Thank you. The workaround works for me for now.

**Comment by pkra** [comment]
This was fixed upstream and will be fixed via #165
