### ISSUE TITLE
Descrepency in ascii code conversion of mathml

### ISSUE THREAD

**Issue by meghanlarson** [mathjax/MathJax-node#94]
When the source mathml has ascii codes in its elements, for example: 

```
<math display='block'>
 <mrow>
  <mtable columnalign='right'>
   <mtr columnalign='right'>
    <mtd columnalign='right'>
     <mrow>
      <mo>&#x2212;</mo><mn>20</mn>
     </mrow>
    </mtd>
    <mtd columnalign='right'>
     <mrow>
      <mo>&#x2212;</mo><mn>20</mn>
     </mrow>
    </mtd>
    <mtd columnalign='right'>
     <mrow></mrow>
    </mtd>
   </mtr>
   <mtr columnalign='right'>
    <mtd columnalign='right'>
     <mrow>
      <menclose notation="bottom">
       <mrow>
        <mo>&#x2212;</mo><mrow><mo>(</mo>
         <mrow>
          <mo>&#x2212;</mo><mn>95</mn>
         </mrow>
        <mo>)</mo></mrow>
       </mrow>
      </menclose>
      
     </mrow>
    </mtd>
    <mtd columnalign='right'>
     <mrow>
      <menclose notation="bottom">
       <mrow>
        <mo>+</mo><mrow><mo>(</mo>
         <mrow>
          <mo>+</mo><mn>95</mn>
         </mrow>
        <mo>)</mo></mrow>
       </mrow>
      </menclose>
      
     </mrow>
    </mtd>
    <mtd columnalign='left' class='notes-lc'>
     <mrow>
      <mtext>sign&#x00A0;is&#x00A0;changed</mtext>
     </mrow>
    </mtd>
   </mtr>
   <mtr columnalign='right'>
    <mtd columnalign='right'>
     <mrow></mrow>
    </mtd>
    <mtd columnalign='right'>
     <mrow>
      <mo>+</mo><mn>75</mn>
     </mrow>
    </mtd>
    <mtd columnalign='left' class='notes-lc'>
     <mrow>
      <mtext>difference</mtext>
     </mrow>
    </mtd>
   </mtr>
   
  </mtable>
 </mrow>
</math>
```

the conversion is different based on whether it's embedded in an html file or sent as a single equation. 

For example, https://mathmlcloud.org/#/html5/553fd114dc92e4fd18ef381d . You can see that the description mentions  "ampersand nbsp semicolon." If you download the converted html file, https://mathmlcloud.org/html5/553fd114dc92e4fd18ef381d/output , you can see that `&#x00A0;` has been converted to `âˆ’`. The mathml returned in the equations report doesn't contain this error. Also, if you send the mathML through as a single equation, the same error does not occur: https://mathmlcloud.org/#/equation/5547a7d8dc92e4fd18ef3ad8

**Comment by pkra** [comment]
I'm not able to reproduce this. Could you tell me how you reproduce this in mathjax-node? 

This might be a problem in the way mmlcloud processes input, e.g., it could be due to (over-)sanitizing the mml string.

**Comment by dpvc** [comment]
I was going to say the same thing.  The MathJax-node command-line tools process your code correctly, so it seems to be in your driver code somewhere.  You might want to check the equation string just before you send it to MathJax-node to see if it hasn't been modified along the way.

**Comment by meghanlarson** [comment]
Ah, yep -- I just confirmed that the converted file is right in storage. The error is happening when I am serving up the html file for download. Sorry for the false alarm and thanks for pointing me in the right direction.

**Comment by dpvc** [comment]
OK, great!  Glad it was not more complicated than that.
