### ISSUE TITLE
Check for iojs compatibility

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#95]
We should check if MathJax-node has any problems on [iojs](https://iojs.org/).

**Comment by pkra** [comment]
A quick manual run on iojs v2.0.1 (on a vagrant precise32 box) showed no problems  for tex2svg, tex2mml, mml2svg.

**Comment by pkra** [comment]
Reopening because jsdom is moving exclusively towards iojs https://github.com/tmpvar/jsdom/issues/995#issuecomment-69938758. 

Most likely ties into the other issues around iojs, atom, electron etc.

**Comment by pkra** [comment]
So I ran MathJax-node on iojs v2.3.4 using jsdom 5.6.1 and get 

```bash
$ iojs bin/tex2svg 'f: X \to Y'
/tmp/mathjax-node/lib/mj-single.js:121
  window.console = console;
                 ^
TypeError: Cannot set property 'console' of undefined
```

jsdom changes? (package.json is at 3.1.1 after all ). Will investigate more.

**Comment by dpvc** [comment]
It looks like in jsdom 4.0 the non-standard `document.parentWindow` was changed to `document.defaultView`.  So try changing that in [line 120](https://github.com/mathjax/MathJax-node/blob/master/lib/mj-single.js#L120).

**Comment by pkra** [comment]
> So try changing that in line 120.

And that seems to do the trick for this example -- yay. 

Will test some more tomorrow.

**Comment by pkra** [comment]
`mjpage` is still broken (just hanging). Will try to narrow it down.

**Comment by pkra** [comment]
Just to clarify, with "just hanging", I was actually talking about the examples`bin/page2*`

**Comment by dpvc** [comment]
So is it on all files, or just some?  (Your earlier message seemed to indicate that it sometimes worked.)  Was that just for mj-single?  Does this mean you are no longer getting the error message that you had reported earlier, but now the process doesn't complete?

**Comment by pkra** [comment]
Sorry for these low-quality comments. `mjsingle` works (with `document.parentWindow` changed to `document.defaultView`). Applying the same change to `mjpage` leads to, e.g., `$ iojs bin/page2mml$` or `$ iojs bin/page2mml < in.html > out.html $  not returning anything (no errors, just hanging, i.e., no return to bash).

I'm creating a minimal example. So far, I get a response from `mjpage` but no actual processing but that's probably my fault -- gimme a minute here ;-)

**Comment by pkra** [comment]
As expected, my fault; a minimal example with `mjpage` works after applying the fix for iojs. The examples `bin/page2*` still hang; will try those another time.

**Comment by pkra** [comment]
Ok, we can file this under "stupidity, Peter". Turns out, I had screwed up nvm and I was calling nodejs instead of iojs :disappointed: Sorry about the noise.

**Comment by dpvc** [comment]
No problem.  I hadn't done any work on it.  :-)

**Comment by pkra** [comment]
Alright, I think it's time to close this and open a new issue for making iojs the default.
