### ISSUE TITLE
set delays to zero [was: Make MathJax-node scaleable]

### ISSUE THREAD

**Issue by arekkas** [mathjax/MathJax-node#98]
Currently, MathJax-node scales very bad, it uses only ~10% of the cpu and it is not possible to run multiple mjAPIs.

**Comment by physikerwelt** [comment]
try mathoid https://github.com/wikimedia/mathoid

**Comment by pkra** [comment]
@arekkas we're always open to suggestions.

**Comment by arekkas** [comment]
I've tried different approaches for tackling this, but there are two major problems:

1. The code is not modularized. It is therefore not possible to have multiple instances run
2. The CPU usage spikes somewhere around 10-15% (it should use all resources - 100%) - even if the queue is uber full
3. There is at least one memory leak (probably due to phantomjs).

What I've tried so far:

To solve *1* and *2*, I tried to modularize the code using the vm module. See [here](https://github.com/serlo-org/athene2-editor/blob/3c4c577568f7f49192cc3a7c47ef9a249dd01744/server/lib/mj-single-concurrent.js) and [here](https://github.com/serlo-org/athene2-editor/blob/3c4c577568f7f49192cc3a7c47ef9a249dd01744/server/server.js#L223-L224).

To solve *3*, I tried to run GC collection manually (using the `--expose_gc`) node command. That definately slowed the memory leak down, but it did not solve it

To solve *1* and *2*, I've also tried to use [pm2](https://github.com/Unitech/pm2) cluster mode (which is using the *cluster* module), but received worse benchmarks when using more slaves than available cpu cores. And again, the memory leak did not disappear.

@physikerwelt thanks for the link. Is it used in live Wikipedia? How does it perform? Have you observed memory leaks as well? As far as I can tell, you're using a very similar approach to the *vm* one, but instead using the cluster module to encapsulate MathjaxNode-single.

My use case is [de.serlo.org](http://de.serlo.org) (only German, sorry), which is basically a wikipedia (ads-free, royalty-free, everybody can contribute, free licenses) for learning, focused on math. We have quite a lot of LaTeX formulas (eg [here](https://de.serlo.org/mathe/zahlen-groessen/bruchrechnen-dezimalzahlen/brueche/aufgaben-kuerzen-bruechen)) which are currently rendered by MathJax in the browser. Because there are pages with lots and lots of LaTeX formulas, the website gets really slow on mobile and old devices.

**Comment by arekkas** [comment]
Originally, this issue contained code and benchmarks, which were really promising, unfortunately, the code failed to hold his promises in production. That's why it got renamed 5 times...

**Comment by pkra** [comment]
Thanks for the additional links. We are currently busy on other parts of the project, so we can't look into this in more detail right now.

FWIW, for your live page, the code seems to prevent MathJax from optimizing its performance by typesetting each equation individually, causing lots of unnecessary reflow. (To see how fast it should render, throw `MathJax.Hub.Queue(["Reprocess", MathJax.Hub]);` into the console or cf http://output.jsbin.com/piviha/2 for an extracted version.)

PS: you're Munich based, correct? @physikerwelt maybe we should give that Berlin hackathon idea another thought.

**Comment by arekkas** [comment]
Oh, thanks so much for the hint, we'll take a closer look in the next couple of days! :)

Yep, we're based in munich and would be able to provide our offices in Munich for a MathJax hackathon as well. I might also be able to reserve some rooms at the WikimediaDE headquarters in Berlin if that's an issue.

**Comment by pkra** [comment]
@arekkas could you try modifying `mjsingle` and add `MathJax.Hub.processSectionDelay = 0;` to the `AuthorInit` call (https://github.com/mathjax/MathJax-node/blob/master/lib/mj-single.js#L157)?

**Comment by pkra** [comment]
The fix mentioned above is now in `develop`

**Comment by arekkas** [comment]
Cool, I'll give it a shot once I have a little bit more of free time again :)

**Comment by pkra** [comment]
This issue seems to have been about the various delays and had been fixed by https://github.com/mathjax/MathJax-node/commit/528d8089e566c1d8c83a2b2bd8e507ab9d22c490
