### ISSUE TITLE
TeX Parse Error question

### ISSUE THREAD

**Issue by tiarno** [mathjax/MathJax-node#99]
Using tex2svg from master I get this error 

    TeX Parse Error: Double subscripts: use braces to clarify

The TeX math is:

    \underline{T}_{ij}

If I change it to this, it works.

    {\underline T}_{ij}

I've seen the same issue with \overline.

MathJax itself will work with either format (using inside the library in a browser rather than the command line).

**Comment by dpvc** [comment]
This was fixed in v2.5 of MathJax.  Is the copy of MathJax in your MathJax-node installation up to date?  Your examples work fine for me, so I suspect that you are using an older version of MathJax.

**Comment by tiarno** [comment]
You are correct Davide, I had 2.4; now that I've updated the problem is solved.
thanks.

**Comment by dpvc** [comment]
OK, thanks for letting us know.  Glad it was an easy fix.
